apiVersion: ENC[AES256_GCM,data:n0Y=,iv:8kCQOAjYMx3wYB1HG2cX4fhzNtprz931GakiFitoB1U=,tag:H/E6EkmAIgHa4NtAKnb9Mw==,type:str]
kind: ENC[AES256_GCM,data:8Ek4cIC9,iv:KsmRTrJI8P/ZK7TpQJbA4Oli5S+YfApmSXXbk9UJBvg=,tag:JIU3wucJ82RDhx7APIkDDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:syK7or4Xgd95GI2yZtw=,iv:loiMR3JqfRAeOAnmxDrTVZKS60RURxyRhw9zYN4VYKw=,tag:c9csoz2K1nXOlLdcR9Nt1w==,type:str]
    namespace: ENC[AES256_GCM,data:oROZbM2W,iv:g+Q3bKdbECf4k4lqeMQ6FWgmEBwW1pA+MFy/yjcouBc=,tag:iesh+jYQSZCGURNNdNv0Zg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:1SzmF+kgRw==,iv:ygc1z1fVPQ1op+LQU0KYPITuIeuobfQF4qbWIU8DprY=,tag:szsYMxGOo6Vd4P/LjwEpVQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:TaZVfHDpNlE=,iv:DKgwAenDkncUfOM0lWhJO0XrdIie2YEzEiI+DaaB/ZY=,tag:oPOPuXauqZcKEjvb70GsnQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:4F7+hzcX,iv:WYy3IAzB+HDuwNr+ixv6ZANV925BvPJGpQAbVX7rIJU=,tag:BbPsjjKJVrilCN2ofx+Umw==,type:str]
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:o/wtPdxM02rEpl2byRqKYN4d3KMsMrvTTCTtNwYYu2q2pm99ARcIAZQsye/xJUdN8goSLJk=,iv:02aL2OUHk8GRkGXxwz5uQ4BVePU51fxRHCbrbGuh4pA=,tag:nKFhVzTXcMv/Tj3yvA8ioQ==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S0FnVmxHNmlJdXh1SExF
            Q1JVU0xMWFlvblF4aXFqbzBZK295d3lzQ2hzCkRCR1piazVWbnZUbmZWUGRKUGgr
            a0FUMDc2TVJ3ZEZYcW00ZExmS0VIM0EKLS0tIHFncGM1TWpLRVA0Mnh2RzF6Q01Y
            cUNhNDIveCt4eHV2L1FWdmgrTEZFRDQK4+9o841uNbtaz+cYCu0yQCUAba2K3c2N
            4M51w+6IqWC9+EnlaGF8Rn4wU6wp5XzQiPS1B3LmE7VeFgxckL48ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T21:14:41Z"
    mac: ENC[AES256_GCM,data:ZQF3v9JUmDSXO3W07QK4UkaIcwUPDKGelRSnd009RH/EQ1UYXdPIpiqwwfpMj/mfPVIVhtYP96bSJXTRIm2ZraSShPgAULITF69C/mMB18QpQOIZg7EncOazSeekYtj7Kij68rSvXQDi5puzMqo2gbM3fE6BKfPzKrQwS/kGSPg=,iv:L5p7FClZBbNyYKcddkm2cIh8RHvj8C+NTnCtdEyC6WE=,tag:iRm7Gk3B34DG67RJW4dFMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
