apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: server
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: server
stringData:
  MARIADB_ROOT_PASSWORD: "change-me-mariadb-root"
