apiVersion: ENC[AES256_GCM,data:+yk=,iv:YsZ04hCgrUV0giaj6FAAZkoIeHTjZdwVqxrA+9zpdWs=,tag:Lxz00xOA6UzO+3r9TvT/sQ==,type:str]
kind: ENC[AES256_GCM,data:AgKWrkcc,iv:BbKxCwsaOLw+6xjae1R9zfW6kKJSxTlTX3trvTlMB8Y=,tag:1jviusU8R/XlWgfCKh5lew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TmPVthT5vMQN2Dj1/Cg=,iv:v7/VHbtlmTLZfjgxM7nsGuk6hP++bw/GUXk9qXHXhJQ=,tag:hbYftx0/S7wz9X/FeOxBmw==,type:str]
    namespace: ENC[AES256_GCM,data:RGZcEQ4N,iv:78ciqOnDe7PKq6fl9mC2mUgPibJ6u2Kq4nVccgqkrZ0=,tag:VxJPSvTAUdgJIkfocpALUQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:PWwGu7ZR2A==,iv:c8nVXtYW5zNm3GyzaXZc9Nw0nCzfdm8rEjxaWclyDwY=,tag:JiDCsMsV71hJEb4L5tlyRg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:HqFyEWXP5RxSXw==,iv:Dab0SayuyhqW13LEcpw6VuMGmdpZWgKBY1I1RQgF944=,tag:XF1LXetUF2lylrTEbT8Vvg==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:BMVinROa,iv:Rwr07AbImswF8cBrsN4xyJ48v0DmeIaQWpPZcbeiXzI=,tag:wLSkQG9NdBORIr/4SoLrXQ==,type:str]
type: ENC[AES256_GCM,data:hdJiyLLd,iv:4IlqteYt4f9HgoF/gcFL2fFh8d5COlhXn+NYdLjAeZM=,tag:t3KqgzJ4QZ03peO92zIHJA==,type:str]
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ezijea2cjavtV44Wx4v6Y9KUqV2xQ/d5Dh/FdTAHluJkXByE0DHi/UO3sTQGljgZDA2GV2ht,iv:TCadeOHukSPAKz2es1D5dsR1jqWj/tZTv8/BCTsaeYk=,tag:PT/lgU0B8XOZrIS45mi2Bg==,type:str]
    #ENC[AES256_GCM,data:G4J3NLwZuXLDhrI+8gqeakKMkPhITvF/9stjhN5eMvm1YICXr4+f8k+ImXo//05IL3WEM6A0QQ==,iv:UpKKTw2nwF9zkncyrxDLGDoqlsciJ4ysebZ5IHoI1ys=,tag:Auo1VB3W0ynI+flOQ0LC+Q==,type:comment]
    #ENC[AES256_GCM,data:osFf5fGTkAJHR3IbAnlnwdwt0Vfj5T9ybRwd7lGgrZzrqSh8l1/5diny,iv:LPwimeigl2fxRlATCNwJiPcKlTWa/kLbwZJTfd9P9pg=,tag:MC9yUQMT/qy8xo6vyVC4aA==,type:comment]
#ENC[AES256_GCM,data:aGVPionGc3PZ/6lb3rqdumOMV8mjSvLxf8gLZBBfV+l8znLNiIoqPG2Beprb3d10,iv:thPpp2FBuKBJtRmZf9qAdjhehPOUwyymYCbkshPu26I=,tag:Pn1CkfDQ0LJmj6MTRKNa5Q==,type:comment]
#ENC[AES256_GCM,data:ycqxg4zUxYUXfi93699adpV/HUVUn0pqLqLJFo6UI5UjUYxT3xar4g+FlaX/6GcEAY2mpTizNZA=,iv:y343pEooawRJVL7k6R8jsuoxT4hOsgpSp9kAcsEcT9U=,tag:jZHiFYWz4WIxG82SbNKo2A==,type:comment]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbkQzdjJ3TzNJbHRTVVFy
            VSs1M2dZMTBLYjlJMUd2dkp4SElvN3ZtS2pvClBsUHRTUklFSlZ1cWkybmowbm4v
            dDRsZ3hBVDVySFBnZEhVcVZRMDlyWkEKLS0tIHJnSEx4MUdFVkRaYlpDVHM1d0hp
            Z0Vta29sSmZ6cnZrZER0d2FXR0dRZDAKUAPBVB9fOdtxAkbi/imwL6P18Lweyi/h
            U3Qo43HJdtxeTKc4/MQ0BTU5SgRMTcZXzvyisP1YjzHD6/XNhVy3UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:43:49Z"
    mac: ENC[AES256_GCM,data:ylWcxqB0CcNPXYfhS6wTivYQ9MEMSMhh49TLDKyZWlKfEBS4rfa08zQ4cmcGrrkt9IaEC4wF7Bv4ZXYIez3FmMzmw6xvAxX9z5NDzyUXpiZhGRtDUMte7TpMKPOytrAbWMgo9iHZt7rLfYxMupddzEbuwwPwCoNdYDvz2fNYVaU=,iv:bl6ss7rWOH8+/79l0wccaJ5uHQebiFshiE1O+RBX+q0=,tag:6wXXW1XsInXcVgJ7op/4OQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
