apiVersion: ENC[AES256_GCM,data:deg=,iv:85P4Q1SeIaE6yhmeMZ3qYm3cqXFnWrXPZapJXQX0EGc=,tag:zN+dzfyW57ypLvrBf6r04A==,type:str]
kind: ENC[AES256_GCM,data:uAcpUQgE,iv:U4dFuWKN++6Tn6fGfSmLk2z1ee2zRoqQRR/2j9uENCI=,tag:/gwESzo35BS9Z/41MZXmMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UaeXYS5OXM7GNbW2Sy4=,iv:O/C9HuOZ/QnHkqtxmv37YFPPqNtgouTdWOf7TMlzxes=,tag:JcW9bPuDnisla20Yf2OtVA==,type:str]
    namespace: ENC[AES256_GCM,data:A2F0v70/,iv:eHAkj1Eq2sQj4KPrOExKGC5j/b8sHkDszQpuf4Rjib8=,tag:xNgyQPwLkqZE7ECkmvSNeA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:WRuhTGmOcA==,iv:gAoQJIeaPKYxCRP1v2nQXZEtkzKcaxn/6EWAXHHFk1c=,tag:zGEdyzWVdYj74hm+jCRGTw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:RgCpBTa72zdM6Q==,iv:ny68ooMgoGH3O9FfRBvVZiR2jLNS21b0Otka6TfBnZs=,tag:6Nx00ewkBFcCmPPGganoCg==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:HgrKNgeA,iv:VAy9JFs1FARy4JHvPI0nNqnT2E9JX8pzAY0tOBSBTUc=,tag:Xhg0HQsLyTuKkXXt+pcb4w==,type:str]
type: ENC[AES256_GCM,data:7iqjrq72,iv:KHkqa6NFmQ8pbLx2pdfAcyGY0Inu5kXwEd/tbSHmgzY=,tag:AHfT4CtF9KBMz1zFW7iEWA==,type:str]
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:9yGLVwaxLswTzYkuINnauCg8COrEA7ZJhLaIAz4NLvh8Pf+3V2lww0x0rSvZoaIYOR0k80Jc,iv:xfi2ZC+ClGdHtw/WwAL2SyJuLTneA6evtQfMKqtF8EY=,tag:Ji0M7lNh6xU1DwxtVftUHw==,type:str]
    #ENC[AES256_GCM,data:upX/eDM+C9w795uJuu4Pfey1Bcrzb3E1vJDC8EkrElXQFAADUObGqfxAHqT4V8vOE7Jg4pKXKQ==,iv:wLudCLeIFbSJrZ95hhD3d+f8+qh6j3Wa2sle0zFTTZ8=,tag:aQ89C3bCA8l4MYQ2BoAoww==,type:comment]
    #ENC[AES256_GCM,data:fqnbiaY117JY70DZqIWVkF6PBHAYPAQVAA9K7gkMz0POx5oiLwwZalwB,iv:jbuUnGzJwaIzOZrsdSNW9/FG/2gAbKkTLUN70fg5F1w=,tag:ZVM8j1gZzFzsTiKsBWTLXA==,type:comment]
#ENC[AES256_GCM,data:MTzDmDaBQoLF0slXXpRSrKg+cUyR/FOTS9jEHRM2D3umiIsHytfbt2Ai/x+EWWjR,iv:ve/hbLfxjFr9GRDDHYvLp30xP0HmR3par1O3shCrCmM=,tag:GX6p5rSzqWy2K51Vv2keXQ==,type:comment]
#ENC[AES256_GCM,data:OOBX/cThOadrBbOkgskHR+AxdVj+ktjJRNEGmJua2uEhrbWsBbKShD+QoikNRBrb++oG6xA+SbI=,iv:hvbLaxRXdBfb/+TF555r2wokj3beUhvQz1mCMYYW54Y=,tag:o19h6JsD/qsJYgno4BymHg==,type:comment]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSUc3aW9MSDQ1RGszT1Vi
            MnY5dWcrVDV2SEZjR1BXMzRMNmd3L3dJMUdjClIyNUU4OVh6N0hPV2pES0Z2SHQ4
            b2NmNU5hVnVkdWh0SnB1TXNFc3VjdkUKLS0tIDJlaG4xeTBXY1k0dHExRTVpdUlM
            MXh3NU5RbitqUjdYcXlFek41clVobDgKHtXuePPvPVIRc9n+fdep8ux2cs8Pkqax
            lF/DmhdkI1dNElPFEO+x6tr8dPKX06r6wMrzgvrGQvGHSoAfxEnd4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:y3wBbUKpsjUMX0F9jXZ5pY8jq+SlkTPfNO0IApgkCuYgWUcyVc7UbJGJCPg57nZrUO8ejij/TJBrI/UvrJecLPuye5wmPa4f0XtQKq9PdUnrplZas6RXQx9m1x0nvBP62cbzUBVJoqILfdWACff6GZxyeR7cQ+BbQfruAZdYZv8=,iv:7Y47idSa8ZTxt902eCYSd9+reunNa8B0A/pnOjgIz30=,tag:mpcGxbiD11GtEH7tmfJ32Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
