apiVersion: ENC[AES256_GCM,data:lZ8=,iv:DOLWXZ/v4qaCcHT6iWlIOohYHOWkYosurdi/C1gkQF8=,tag:MEQnsYig7GOU2zXde3SqGw==,type:str]
kind: ENC[AES256_GCM,data:sbDotTbr,iv:6FONtmrt+9pyL7lvmaeUR0MWO9upCpRJ0vRIrcvJYAM=,tag:UIkoBee92lhuAUfjxVC9Zg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lsPYoNFmmBpMdMqZaB8=,iv:OVqK5mkxr2/SOBQHb2B7CroVY+iqEOtU21MVGWxprq8=,tag:MkZYvGNf+WR9m6pQurxrFA==,type:str]
    namespace: ENC[AES256_GCM,data:Hjywnk0W,iv:kxmE/m4VUTkFOs5ITO1ipW4fOJ88Ls2LbzriqoX/0+0=,tag:WDUiGsREo81FuPvjAyPcMQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:/bCVYNw7Hg==,iv:cDFB5h9Dy1FcVneLI88PjyiGUPGStq3BqcNOh+OVEV0=,tag:37YhV7CUjZjGyWQOnuBrJQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:gMRZR2Zj0MCm5Q==,iv:xzcSqyKX2rXG8+Jv9VtZLCzD8MrUfk/RlZxX9s8d1I0=,tag:o2C7mGTaQsTaD7Hn0n01QQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:9PtbFx/9,iv:o5sk/9SyBXiuUKy4xEvnlExQduMyszsumh1miSP2k9Y=,tag:jJrtpP78vWUhTddWDVZW1A==,type:str]
type: ENC[AES256_GCM,data:oGcH+HGe,iv:Wl6gdtX7GEEDXSW2sovtvDPFyjEElTAd+teGwkVFrRA=,tag:GHt4t+y1HibVrzLozh8www==,type:str]
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:/iuvITAxl5ZSnVPwEz3FWXE0djBI2wTjhXZB+yBpi5mZ8ExMSHLHnYf7ihSowoxULH5qoWQm,iv:Rs0M6G+lSoyPizsB1/FSehScJ6mxM+m8WTgEVL6kPL8=,tag:mVDVHHKZ5PcIZhuxqY38gw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:bQlZ/vnmmEAV359Div6HXogUCq0JE7yG+BcBs3cN0+UmYRdbM6WFaA==,iv:CS2K7kDbGwDloxUgdvKPMHlkBmqVVMN7ickpOTzmDOI=,tag:o4bsY67/U87a3JYYuKkAAg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:e+Z5lexR5XCFt0ZQnG0btsP+iF5vT2U80bVu4Sa4i4+H12RrDgGjviSuEBNqsLf9mPd9G/SAuH04ZMAryTLpUaDUVDdHx1Cd/Hbzk9/bKRpRjOYGG2VICzMDO3ZSeWNsuIqx5o+4DKf3hpqynDXLDuq52cYsIJUDlRhoz+kTCNI=,iv:7XEIaJTI0vROvkHlz1wle+b1MCZ4eRp7oDXICJ2G6+g=,tag:dMwZC1pVbLMQXi0y/cc5uA==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzekwzZUxDcGFWeEZPN3JH
            SVF5SVlkUStWblRkVW5Sd3NEVFliaG52N1U0Cm1xRlljQy9iZWhKSUtYSENVb0dq
            VHhWV1JoQ0ZvcGkxdUtvei9tNVdneEUKLS0tIHZpSFpsWGhlTEJWUVVaWDRLNDV1
            SktTL0tTZFhDSHdYOFJNbFNHcTFiMmcKL9bHBrlTKsvgslEISBeSPArjYrAjYLKj
            B7hwS88Bev8uznAyZTcLlnGV9R1xsyMzCaNCnnWuF/9GnQ2OMBWUcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T00:55:53Z"
    mac: ENC[AES256_GCM,data:xObSkDs/+nWBbyxbKjueziKEy5ncaVt5RjbR0CJC57FW5LivZgiIP/wI2c1TNyydUtbn31Bkld3oQCrKWbB81NUIvkwR+7PLYQHDdvWFFTOHbTnnM+BtrwPHBOLR3PuCRpgdflY35xKCxKbhh1nnjV3oX0pUaQ/MPGo9QSGgyok=,iv:2VtyRwOjuF9+iiA62BCqw78aQfhKYHDfTwWI7GA8pIg=,tag:U8H4uhCUSY1K7mbvFVVLzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
