services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    volumes:
      - ../data/mealie/data:/app/data/
    env_file: mealie.env
    depends_on:
      - mealie-db
    labels:
      - docker-volume-backup.stop-during-backup=true

  mealie-db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ../data/mealie/database:/var/lib/postgresql/data
    env_file: mealie.env
    labels:
      - docker-volume-backup.stop-during-backup=true
