apiVersion: ENC[AES256_GCM,data:KX8=,iv:zLVmk6fjZHEsFnZINWUPvInWNJVyx8lsdA/r9IQCOsg=,tag:BTi5HFk/wNvOGe1MnQdH1g==,type:str]
kind: ENC[AES256_GCM,data:ShPrqRYo,iv:Rxy/HdfHtXqDuUrtzDVagdO+1wnnhFVP+du/hqFANtM=,tag:ZpJ6r3mIbB4cdjf4ncU7pQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wv4wivGuELVaugE7wQ==,iv:6pG+KpAT5W/2mb+y+g/tqE2HRefeBoQsIi4Xg+vKnHw=,tag:h0+++i0mEZGY1M3cOOwnFQ==,type:str]
    namespace: ENC[AES256_GCM,data:datwHSPk,iv:LR7hCwKPwSQQ3VKifgmsx8nD3lRq5i6aCC8QWYNj7bM=,tag:O0GUc/11igOYgFRgQxZqzA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:phYpRvDF,iv:7wwks8N4NtfAPqQidGp3KhZCTG2qhJjAKHG30ZdSE7E=,tag:YA/XH+HrN0zOL5ejifkScg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:/zY/bZ9Jgw==,iv:QTHOH2t8FfLn3bbJs5VKL5rTEPQnhvmFB6jROMMJx5k=,tag:BaPSKVlnZe7EjmDqMmO0aQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:8ghoQF8g,iv:TyoWNZXMUIH/lEBO5haLYup2TvouHRyX/q/v6nkR9UQ=,tag:QFebydcqkfyX/RA08Z3oYw==,type:str]
type: ENC[AES256_GCM,data:LPay9qF+,iv:DiUiZnz+9GaKseZFKMQ+uqKdwJRF/ADGgUUD5y/BcOQ=,tag:vth81IVKqv2J9bTL/1nDng==,type:str]
stringData:
    GPG_PASSPHRASE: ENC[AES256_GCM,data:ddxAkKBvSafIF0ROIiSYEoaFPkpoW+D3w4ohU9PkQf3AvNjv+dTwLR7WZTrXnUqjKjo=,iv:qH38jYH3LJ+Y6LRH8QykQjwYVCDJMOudZq9MVukfd7g=,tag:vpt//M4xoFKLYOIPJ5Ih4Q==,type:str]
    rclone.conf: ENC[AES256_GCM,data:zlS2WaZ5JPQLcnjGQXhSsXSgIwoFM115Sn/HGP2QlK9vhWxTvLDtq+UqbsVgWDPiCdGaB0iIuknyy4uAkVbNnwMntau+qJd0XeoJqJiOLyaYs83miB667Ktcb4ZSbKPVchlRWwYzuheQ4bNyClCy7g==,iv:VSWvoQuwXiS8Ufps2caYAUfozYSqzVVLlkF2Cg41u/Q=,tag:CGvqRXLq9KysdwL87H1O9g==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c1FuRFN2cGx6cjF5VEJ0
            WEE5ZjJ1VE5aQ2ZvMzBEejBKYk93RithMzJzCmtacDhLVDNSTjd1ZElZRCtZU3Jk
            ckczYTI2Sk4zSmZwYndEWGMrZmFPUVUKLS0tIHkvcFJUWEgzU1ppRlRGRlRPUG9E
            SGN4VytsY1pkU2NlSGhyeUxRUWlCeEEKRNnHuIgBwhsBLRzWxvgYiS55DgKYOIiI
            jfIMak5IgvTU2m7enkI6mJE1ZFU2V4yfxSOzLKT1ESyD1BJp4id0xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:43:49Z"
    mac: ENC[AES256_GCM,data:h8fOHAilyrdj4zoZ60f051ht+0N2pZDsaZkKRm+P7zr9qpE1+yfOrdlN39lAjA6npz+VbDUPXv/5LLwu+mGFqShXCufYnDbrv9Ve7me0A/laQQoAeOuWF9UNYZWghnkxcJ+YS/HpMqUJqyUNMtNoLr86efooLyCTjIsl5sLnvSg=,iv:P3IpzlJoEZ2Lj/Cnl4QRiKFY9D2r6plbZ8OW44MaR50=,tag:4dH5uqHvou4qzw4OTf3kFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
