apiVersion: ENC[AES256_GCM,data:xcw=,iv:HwK7zUwMQ2bMpLrHL5ELD/OEGY1o4CbxivB5mJqAaD0=,tag:cfuMZnvaSrt+SQJ0vmYZtA==,type:str]
kind: ENC[AES256_GCM,data:qW20/kAX,iv:Gw+2YVLjzIP7grReYZU+HuZG8Fd9SBoV51fiMZNiqU4=,tag:tBgmQdU1dcNiE8DTwnCfRg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZZOCqPLGIgwe6oMEJA==,iv:Mlx5IpyDRxJ1dg5drA3YPDJBpOHUXEr3yP1Rbw1tjq4=,tag:2Btmne+iTdHwkQ/P0IoOmQ==,type:str]
    namespace: ENC[AES256_GCM,data:fSFxxKW/,iv:lLZE7xL48lZrLNyIQ0owh6sApytowWF0T3SHWV1Y1ik=,tag:X5tceFA7Jjx8ppyN1eTbzQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:IHg1eCUP,iv:6DtGR0GwFHkFaOY6kvx6gp7p4S+JH7CGfAMOfiXM90k=,tag:+0ApbqFQMIMSK31xtOjjnQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:2lLcuQJEuA==,iv:bjZV6WFFb8uhxlerN89n/ug69wU5sdgvMGzTbM4Wf7k=,tag:rrslEC97yI/gRaFQxPI7Cw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:ucazPc8i,iv:QHhmZ5MICmf6wyinE7g7JgCzPvmEH5cnCmG0BnPbswQ=,tag:pHzK48K+0wk6IufbmhxhEA==,type:str]
type: ENC[AES256_GCM,data:7sQZom3c,iv:ttLMH2wJ5NcJpJvqA8E/WgXcH3ETaosjkBH8mSX2Qfk=,tag:6pfHvvuhJposSC91STLTgg==,type:str]
stringData:
    GPG_PASSPHRASE: ENC[AES256_GCM,data:exB2lTnTz7HYqBjDm42wjkeasu8VwwtrJvv8kKup1/610peHOdO8pGsBZG6XrJwoagM=,iv:+7kpyokHyucYBii/o8lHX0vf55tcgDRhlDVSLUeUEKg=,tag:SYR3IK3qGl82GhkWiDufYA==,type:str]
    rclone.conf: ENC[AES256_GCM,data:FjhcW5+ISMz8R9mDk62q+PB26HU46xU2XdSkPEygf3uvUeWPACCjDk7si8yJraC7PFmqsHSql0b3pEa2qxex1WUp5y9SGI4oxUvCWhq+dQb3TyKWv85YAzXhz8SOBW4785LStDMpsDHIhc292OBYcg==,iv:i41CNTdhDUpHu9JErdOYCKmXOgB9VpTtg06pM0YkiPI=,tag:tOaJpKvJLczlR1oCcgXheQ==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVno5bzhMZEd1ZTZNSUhS
            VTRQQnpoNlpXa3E5MTJBdlpXTEpqdXhGc25BCjkrMFRGSmdPS01WU3RZUGROTnRF
            UjVxazQwWW5KSUNnUTJJUzVabWIwZzgKLS0tIE54V1J3U05DeGdobUZrZGpQS1lF
            ZmtwOUgzSGFxeTQ1QTI5blByWE1URHcK2an2RtJyYPOhI0QCXBNIC8u2jZsANVnT
            txm+lxo64bJ9Xcru9Nv2aFnvZwjy4yUDlFbjNb1k8XLidhjni4N4/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:/j7QUc3V/22D2l9849rRsNKRFcvaHd3OYHElAgl9N3/qHT0Q1ssn+hEJBTLnD9gWd8zRFAE7U6+lRpQMPFwBOUBzXnjESu2en9KT7cReCji+IixsgSFhqbG1Pd7w7W3N0TmbyeCqSXnPunIDXur4N+AukaeJ0Ey0cOjJp+yK1i8=,iv:pzz0Q5I03DmfObj45Q4wjJmOCv5eam260kn8Ik31uNg=,tag:g6tw+oiKtj8osHiVKDQ3gw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
