apiVersion: ENC[AES256_GCM,data:Y0I=,iv:qfYzr6tpl0iiOGzaVzvSUiG2jq9+q0X7N9eHOwSdy+Y=,tag:GdSF5MtxfPCTJJIhQME5xg==,type:str]
kind: ENC[AES256_GCM,data:S6qFHHiY,iv:G5DQQ7tjftrMSlmN2jA8LN6i/0py4Tgq3Sz6Id6VlO0=,tag:MLSPIra4njWbJoPH3CIzjg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Zi+ts5iVqpSaIRW8Sw==,iv:trPu4QKdj80iRbwpSva2u65YuOLHBndviIDLIhAzxjU=,tag:rNdxgELrK4Xb6vYfIRIs2g==,type:str]
    namespace: ENC[AES256_GCM,data:ui969/Cx,iv:5EQZZ6T8+R+GT3zo3EoSa7j4aq4mU+wTvNE7HeQ0WiA=,tag:mxhFUlrQVeWpWK+H9BolUw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:gwvJg+/i,iv:I/M/X/XW8mjYFKjVBkt9keGzBJbtUPeMq3S7weArDZ0=,tag:flCNN41x9vNtZUYnJig1zw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:2dbOhpz8cg==,iv:Fl0QzeM4PjITbsPbtVX7CIoXg3YU6OnCyVtfU3D4LKI=,tag:23h9Ky6ZQUEmF/kM6L8Qvg==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:4FcyD5cV,iv:JyU13m0eGKAmJOhM6G+5HQaYnVKGplcAiu5YrJdO5bo=,tag:QWQDinr80Zov8p6zpVKzbQ==,type:str]
type: ENC[AES256_GCM,data:Z+LGMbXs,iv:9NHfnZoz8FkB4gPTcHv7p47I0r/xzuCheStutrrwvUQ=,tag:ann8G5s14YVJ+Y2rlQoE0A==,type:str]
stringData:
    GPG_PASSPHRASE: ENC[AES256_GCM,data:Iujd9mUUPaeQkooxGJbLCe/p7iFgyuoUOum/4KhA4mh+/cHa/HeX28YsUGexi1EZ+Wg=,iv:R1l2bUtP1//XTe7tc3hKC2sfgkGNy8ayM1okk6EqG/A=,tag:WU9UvQ43ybTFXnDcw9pPqA==,type:str]
    rclone.conf: ENC[AES256_GCM,data:vxcajN5JVxSIm7KpuhuAYPl2/4EXqMHQcx2RyBDyac7J4IczxOjNd4qTDUmuzVa9er2f/1LpsakUVM2GRn1lHeGQlrSNCpe5KIfP/YLtmwXHmYTpgkToQudiv1Baxp3wzeVXo9akrxwlfwbXFGnOVQ==,iv:1x4IWgiPyerEQAc2yX78/aID7oZKm8Dg2K9iYNwRi14=,tag:U6hCGTBEabAniO3Z5/hZig==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNUUxUjdEZ01VNXFPa21q
            ckMwRHdwOW5VSEJzTUFkbVpRR1dhMmF0VWw4CjBzcHhYTkVPaG13eVZ1dFFlVzFm
            UG1qTG11WU4wVXIyUkszWmFtNmVyU1kKLS0tIFBKZUVUTW9vNDJ6aWhYMzRnODYy
            bG15SGE0NG80Q2RiL21CRFhlQU9SUFUKqptxCxclJeRT03CM6B0bscsBErevoukv
            p7CeQT23lyJktGS6q5WPnfL4sBhS3ZpDnxmmM7ZAkYVnUviubn/TpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T00:55:53Z"
    mac: ENC[AES256_GCM,data:fzlneYHwGsJfE4ZU0RHqG2ss0Bx/1dh/B1UjAUeQRY+jZpQcWhSMH4C87TwYd1GOYQfdpQI+dj6TR17f4IqxbTFGdpXmrhZmNLQr6AoTGKcTK6GOQcAz7+lJDckH4ajQDd+eOuI97WOQP8dp3fj57wgf3STVGVYg3UyPerRND5Y=,iv:k2Sp9o7j66uifGbRdmYY7abnljJyIQejTqF6Ilt5raE=,tag:RgkQ53rRXSWRXyg92nYDPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
