apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: server
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: server
stringData:
  PAPERLESS_SECRET_KEY: "change-me-very-long-secret-key"
