apiVersion: ENC[AES256_GCM,data:ZS8=,iv:iy9X4i+uhRgGo3Tqv4qMljXpXSAbg3b5uhF4dIWTKSw=,tag:62t9mKthxb8reGekig3v8A==,type:str]
kind: ENC[AES256_GCM,data:8utXucz9,iv:KKHuFRt830tNVgXpogaJzJJvLKKNkB8vYj9Ev58bhvY=,tag:Ip+l5iRWL2d/ZerirJ7WTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FQfsmQ48DrQHv3gcsN5+7g==,iv:8P5YHgnwWdANGGBdqxvm0bNu4GgiKQzIZOqkd754WCk=,tag:/FoHb39+K+v474ZnkAZL8g==,type:str]
    namespace: ENC[AES256_GCM,data:JXBzKqdM,iv:J9ItY9cNqHsgkrCOqnE2QpoFl04c9Kc/6Ygo6hkKJKM=,tag:OzDTpnp0ov7YabNls1roRg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:4nF+9umwWv96,iv:hy/CKyeOxVfiP0fkIWgYz+y68ovaVLc/NKqF4kLaxN4=,tag:rcpUkfEGDcm7rjuRAD9DvQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:GX5CaFxi,iv:Gglf1/YlPQAKysX+pEFDdDU2luWJMrAwdyY04kDW34w=,tag:8z0MVWhzM7yI66U01oo1Fg==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:gr4dKvY6,iv:eFZr5KiX5Upvfm+wZc/ImixLxP/bBehAyo5watxaMt0=,tag:L6N1Rhrj+JFZeFCreqFPNA==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:2KSuFY5tppVXQygfGrnBGOZGIkmjMcO+WAqfeYyjIyEVtdAwucfyq3Fz90p1yaYhadDK2+xi+euFox3BulA9YDgAEyxvWqndFIoyijImDIo1SvlRIZtdCBszqROT/b6R7Pjnm+2sSRa+51Hg87+FsHDYGf1NYkenN3nVL0awPuM=,iv:kU1SOI2h2nBo/NS9s+fPAVfewAnVzb3Sy0jjqcUCorE=,tag:5czatswOwHkGWN5hQ0e/DQ==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOFgyT2h1cEVYUjRKVGxy
            dzNtdGVBbWJIdzFIZFh5bWdQTHBHQklRbUY0CmMzZUdSRURiVTJpczNhWk9jTWJS
            QURSVjhJZjVVOU1zeU1zUVVPeklKcUkKLS0tIEZqWUxYS3V0eHVFK3R1T3A5L01I
            WStwQm5QSEJDdjc1UU8xRldPSDFkM1EKMAtCVA5XZ7NZ6E3pRPOYCyx0PjtCeg8q
            dBAsiSezSUSAraeVCxkbKrNa0yQk9Ce8X7Sqr5G3FLXt6RE3xVtOOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:43:49Z"
    mac: ENC[AES256_GCM,data:xQUYY1L9D8qVDrI2zZNTmGWUJjKH4nPv3yaJWBKc5lfcEzP9GMvgDBL4fy2xtzr+tbp2B6fnLd5E7y3o9JTHRiM+ndcvpkM4iBE0pc35yRkEobuNLzn0NWfYqMhddmSGSEgDBZenAymTGlUv6eDeUEgL687uim3gfIhoSMTt6u4=,iv:VoeRqxXQDIshc6OqUsepiweRGm4m6HRy9vimjtSpzWU=,tag:XmZOYxdza98/HIQvpb6XQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
