apiVersion: ENC[AES256_GCM,data:fCs=,iv:Bc+dxXU0Sn39c0pEUqFoZPKJgi3tymSHBcrf84ktdsA=,tag:0AzwtjjFSvSgspIM2QAY5Q==,type:str]
kind: ENC[AES256_GCM,data:lWUnd04r,iv:theaqgW6wwp0V56xSbGq/BoRrI9FN4sA3wpDD1jBP90=,tag:2j9wYBWjUbd2o351TlU+gA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gwU2RMXwKuCGwXnCXHUn+A==,iv:Z2KG93n16M5Hqe7LWNRHYWhHRtAKOAJM1PwBjlPNPHU=,tag:k7Q1iTu+EgNFJf2w4vOkaA==,type:str]
    namespace: ENC[AES256_GCM,data:x/As4RIj,iv:rngjfSI9AYSivsEUfWeimxN9Co/ZmDJG36JS4N5Xs0A=,tag:JRsSH30UVa6s5IuNmn5a/A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:EdytE2iw7Y8+,iv:F4NoHAa+pNGWcLwUXah8NOUzSDVYvxKf01UvCafhfWs=,tag:sVc0dazzNy//LAw5sn0yIA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:eZaKM2LS,iv:JpZvOMfgSX+wfRtY0VQygBAd97ykadcDzqv2TlHWjfw=,tag:8bB5OkCnPfWLaKVQ1xgrWg==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:ER34uexL,iv:CIe2ZP5kLzjJMrL0OFsBENpvM63/zuscTQYQtCPvkE0=,tag:Qv2funhbNM9Phtr6xjS7mA==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:qMZ2rvA3Iex4B3IotakFGE1yUfvGxb2KYPn59qzNzlqcUR+UcMm+/EgdRgeT4yZxCOOM4U1+ZpJcgg9VB39oeX73FTYKMsgUKObJZ3+VcHMMSOZr5YQlRqos34Ce6DE20AfXtI4Qu/UEqtlVEcfPrTBQj+JOICyGdEybSyJ7r/4=,iv:cZiH/G4eaDAB6CSlc+wZrZGjl8+Ojefo+s5lFzNFYNo=,tag:05iZka0U+3DHimw9RDye/g==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZnJkU3VJL004ckp4bzFw
            RTMrTzQ3UkpZcFVvV1lneFVWUHA1bFl5UWdvCldkeGpucGhrU3RzQ0owUWlOWjkw
            NEJDM1lwbGFOWHJUdVFsNXJUcmlBSUEKLS0tIHpBWkNyUTl5UzJENStiVWtGWkxw
            UFZyMUNPRDMxV1F6N1JLUTF1TUpReEkK0KHLXQDEf9ueMb+LZ4Nr3uDKKqdUlJFd
            33rsZztCMGb0YMmzcFlKow8QP+nEVC1QSsDabjx5NPaWdAWQEOpI5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T00:55:53Z"
    mac: ENC[AES256_GCM,data:FwCq/OnDqggxR9kryO7YqugqQYK5OlXbyZLB9eIyXAXOpy1ZF2zYflWhESH2qZv0yVs/Kc+AHvo3L4M+n420FQoEYWgo0N7uAK7JiQJ15qqP0gqyj1WUgFSG+1Eq1HJWazOD1Z/6IjpYZeotH1jAjyw+MKag4cx/l0Lp5kn2bOQ=,iv:IdBAj2gLGNoLEfCEL1bPO/TImkGuCHUVO1qPV8I1Mxc=,tag:KGZkNvS4f+yvE0RKsEDiaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
