apiVersion: ENC[AES256_GCM,data:Yt0=,iv:224jSyh1+ELRAhn7EB7btJznflw81t1i+yuwYZuKCfQ=,tag:vGAd6lZyISgXHukNSlD6QQ==,type:str]
kind: ENC[AES256_GCM,data:sVqubnvj,iv:4+aC17NgWUTIc6rWm5RudY/uN+2OuQQVanXKtlSSk20=,tag:iDWPhpCuztCB9AFLHi4M6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aHs4/x3CsOriULMibZuzZA==,iv:/OfsysUPL1SDWrXREJsWh0MhiE05ggPqcKRGXFSOCqM=,tag:893a+pPJ1F41UBSUqn0i6A==,type:str]
    namespace: ENC[AES256_GCM,data:HfGPS1WJ,iv:eETpJBsvjubPa62psMIIGsEB8QNN+M25fjAWkQkpgSA=,tag:mRcVlH9kRv/K5+Fhf3dwTg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:KtjokYkGoiwX,iv:zfnsXDfMQVRG2B6OB5sdoLdOTJSO2NMBAB0JxfWuLDw=,tag:UDF66Y56PCPDnPXcyI1dHw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:PtppxvsV,iv:5xUdWPYToxUE/YpdbDMiydM+3UA4OTT+hg+pR3TMvjQ=,tag:zUW59g95hB4fBewXU7atuQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:Pr5TxQrO,iv:LSJS7bIJgImdPVoBcnbMJu4WAc0I0UJPJ8Ie9QtZySE=,tag:WaJSSIVZ7nWgI7btjTl0cQ==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:QgaZ0Fdqbw9mEjfaKGTr0I7XXE4UcA1FTRn9HS17YIizr8sihlyPBlWRHrdyey6+oFQYMkZb99LYSTuvohWcHhhhQdYQ5dLP5xK8y7ehkjW/9L7lX9C2kGyCpmmy4wbyGXaYW8dlwERQcje5f/vRzxMCnEUg8fRSbBlOZsukdcA=,iv:ShWIhsXcSaCh0Fb2syVpV3dBorQdTtJwnpHQDmJlons=,tag:Q2J5yASL9pkIVpZn8hHQwQ==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaXpvVzkzTytYbm1aMm45
            MHRDN3ptL1kvWVFZYTdmR053bFFpYzh2NVFrClR0eFhUUUxyb1lSQmRJUE9KbHUx
            S2pVMFFnamdHdGY0UUladzdDMXQrZFkKLS0tIGFVSHdabGhzQzVpcTdHNzdxNWFz
            R2xJNTZXakpDNFgwNDhEZk5MNTNhbncKpQfwUNT9ISaoHTyjwqHpi3fUffNMPgqd
            OWlyN9PCCAYt+IE7qFuc4vgpXlJBi2dCVlY63EQI87t0y3u/tEJ2kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:Ja7xm68xRfh4nb4+9F21AlUw5UWUmz70/VCK4w+J1RZkCagDvi5TPZnEhZ4XF+fkIquOtzgJumMNJuDlXr3ShiDyCxvpLRwqEw0sw30Y0CIFgr5ryMlc4Ul3BWEkPT4107sg0w3F59AjIQE152/cm90V6MQYVAGJBIk67yDAQlU=,iv:yeIkSiK/ZAySUieCbigtpt/Lr1YYtj7jiLqeDaxkSAU=,tag:iIkj0hGxjRGW57tsy3kP2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
