services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      DOMAIN: "https://pw.d-f.dev"
      SIGNUPS_ALLOWED: true
    volumes:
      - ../data/vaultwarden:/data
    labels:
      - docker-volume-backup.stop-during-backup=true
