apiVersion: ENC[AES256_GCM,data:Gg0=,iv:uRFmfwWTpy8UbbSEtcZ6pVnCjk5yMlYzvZFrAEHwQTc=,tag:GT/M9V/VStLqkOu7ArZaNg==,type:str]
kind: ENC[AES256_GCM,data:9RMDjosi,iv:x4NvvSJaavX5xK/1g963mAwvEmU1ummZXerp0bctSZk=,tag:GatoeKGi81CQsAiuNFCNZg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NQrAppVwRAG2G7Vb,iv:eMQXPpS62/D47/i+zoiNQbUK1ipucX7C93fV7WQz9TE=,tag:q48TXXa6qaZkJbmUdj0lKg==,type:str]
    namespace: ENC[AES256_GCM,data:Slh+SdHK,iv:X4vd4iG/HGiiBHdpR4EhtWrotqMPeTGM/lPMmBrrFbg=,tag:V6EN9XMx4b7oyeEBnw/VQQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:g94slAg=,iv:FfDTGVBc/d2cx6gM8/Q2YRqYWRzPIKKGn1tD8m9qjVE=,tag:TIpja7J4k4wqRfIA9mB4UA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:D3Sgtwb+I+k=,iv:5MvBcOtm+or7GIL9oGfRS9C0pVRHAFToNft7bKIsijA=,tag:af5jlw0qQuKPym+CBIJJ+w==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:5luVACma,iv:NDUa+5ZEvH+C2Qg9xF4ZdTyOLRl2CTjvt1mg5GpcOfY=,tag:8IipuI6MrXitdPOp14cG5g==,type:str]
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:6aNPYya/mQCnPM6Kcecrm8nCGEmOobfuma16RNYla+5TU4LAd+8WqH6yiGR6PHPDnzxo3lk=,iv:9e8umi/VqXVIs0/Y77EPm4rbDX65Gz4PCJi9qWxmjrQ=,tag:SlOSmhsobx4Zn44FaIpO2A==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeWdjN1R5dzFZYi8ydXJz
            VWVEaW9DZjlPajdjbUJ1RTIxa0tBZXpuVFVnCk43NDlEdVM5VHQ2S3prM2hYR2Fs
            ZUhmRFB0TFl4a2F5eDFUWXpGTm8xR2MKLS0tIExkRnFsWUtyaG1RL2RHcklqNFIw
            Qy9URXJMbGlYbEduSm9EZ2pybEpzYVUKsKXWQZuqAfVHS+DmK0I24r4kesVYB+Kk
            ld3ZsI2fU6/m0lfmbWDahGGoAfzumwolaWStl7K5cQq6sJleQxJwjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T02:00:28Z"
    mac: ENC[AES256_GCM,data:YlkHSkUWjVUVSz8aFOgCfEj9O9cVbdRPzcUNKldzgjnEXnCRr2BwnfmufeWDmAcl+Fi2ZFvGmCAr6TNkZK6Jm6Qj3Ha2UGsS3YLR5Tgm2Yxl5siifGzt6rZhRVOmDVAgl4YNb7VwW7lgGp5sX/KJT0wIO7wj5qan8XbvdXgRp9A=,iv:TwDYIB9LWQ4xL0h8rE6UPR6K3duO+CmeGc8DcFdDauM=,tag:ut+yn5FidfXJYQxTIIOFsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
