apiVersion: ENC[AES256_GCM,data:hnM=,iv:DiinYi7aFuqaG9T/aePtcOy0FJvQ2ubt0bU9jS9LDic=,tag:36wg1GAz0spPEdaysnjXcw==,type:str]
kind: ENC[AES256_GCM,data:GRIyqP3d,iv:/UPP6tx40q9o74JIw1pkaQO+wHt0i90HrD/jEv0JgFw=,tag:WN70gML0NlXP49iTCHN1vQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kyoUnvsnrw1yyVKo,iv:+9onrROfDF4pL8T2/ZypZSQrE3+jT/Cflzc+ohL6GkY=,tag:gDzsZtoXp6ppDlzQQB1ZQw==,type:str]
    namespace: ENC[AES256_GCM,data:sxV1JRJB,iv:WhdPH3A89rgXXM017eBfM2Df0mheIQinMWG2pn0wTRc=,tag:WfXRRMRgX8BWzj6pcGL7ng==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:PYV86so=,iv:DSozzF2mI8MQgS+2sqmBro9ORFeW0jjm77NfF6LZlDg=,tag:X/bHrxxHRFsNYb86pNprFg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:+Yw6Fq+E9Ic=,iv:hllMUmJzDqALfOxfK3V5rKajKMkdX6oZOP/jSjitr5g=,tag:AAGjQJQFnglT/h3TxHcLLw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:gHqzCqSQ,iv:tz5VWWg7ushxpFksEAKr8dJU/w6Fn87EOqc07DdlhKc=,tag:2EnJZ+nQOdazR5jwiE+abw==,type:str]
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:Dr3GSsqeNsbRbP24dK5dK5nvBdsOxvJx07UWD371ZPLqr52uTpY/7iwvHFW2eXs+QAudhKk=,iv:DaW/iyA9aA4nrngX/Tb10hjWtPTXH9/9KLkiZvmrdDU=,tag:8/vmOgfj+PvOyzeLpg56XA==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UmRvR3JtQ0pRb3htYnVo
            eC9VOWxkc1ZRaVBuOWNzT3YvOUdxS2lZV2xJCndObDVBczJNSC9LeU5OTlBRU0Qz
            eG0yN3ZMOUFmRERsQm1wR3ZqQkloUXMKLS0tIHJpcHA1NVZzZjZPa2NnS000R3hw
            SjhGc0hXcWx2WURQQUlpb2pWWnlKbm8Ker7dR0ZcE3Vz7rMvT+5vdfWwNncNTR2Z
            SX4Dj5dOra73lDFYINpAE7VpTlOv8izMgl46Vas62IfL7m3maxY9FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T00:55:53Z"
    mac: ENC[AES256_GCM,data:8ANtTMB3Yx7xwdVy3MXvrZDSKUuuEqJ3CCQ6GKfG1TxHuyPqq8K4QmOTD75GnTOaFnpA4Noqpg7n5+CQneGo0TLV4sm3rtmdsUxhd9JHrQtdVDRLpofgtxgjbhrFrnOm7pVhbOig2e4/9ShAx0dVK8WM5btX2zoV8rTzJUcEq4o=,iv:fN564+U33kDaOcpHwf4PG7zepJ8grxiCGuk9+8fOCCU=,tag:YltGIxo1hPVYhw2w3DsyaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
