apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: server
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: server
stringData:
  MYSQL_ROOT_PASSWORD: "change-me-mysql-root"
