apiVersion: ENC[AES256_GCM,data:OXA=,iv:h5gSktaOHzwPXJOAMzpLyHXgEXsgW57uekTAxXknhQU=,tag:qakz3cv7ZMF7Mhz6WTr6+Q==,type:str]
kind: ENC[AES256_GCM,data:zGqKdKV1,iv:O4ERt1mJzNZvasVgUBZNgdqZsK3Li1YBzELtSgpmBgg=,tag:QuZ2wnBDI58UZnDALJm74A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gseG/LOCMAGWqGuS,iv:BHUtPr2GMT71clvUtEAO0irONoKlUzq+gGp8Nb0Qbo8=,tag:9xJ92Tub9RMlwmyR/AUrYA==,type:str]
    namespace: ENC[AES256_GCM,data:cisKDbRl,iv:wkXhrVkrG/b2s2q40XKKmthHEnaRyQBXKt3Cf4Lcf7s=,tag:RaXSUzqhhbuF3z9GjQQRSQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:eE0fa1A=,iv:UwAq4WxuG3U3PhRTYkh6SjWSiJIFBrLsK1djBmG5ZqQ=,tag:gEJIcPEURFXTFMlZSPaE9w==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:/XYlG8V9yeg=,iv:lDOISq8yILp3+1kY6bWmHfxyFrcRc2CE+Kjlz8KM0hU=,tag:OFgfZ6h5J0+vXB4zQXJ20Q==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:cMLEMiYp,iv:kuzJzF4aN1OhSZxBrS/PU2lsfSIMt/ZdRddtsxK8eSY=,tag:FzqgF5Zk7AIxiucCpKplRw==,type:str]
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:SXUOu/WvtsmkHIiFoK0247vGdk6rCmzPkD2RBjIIJdGAgJjhgeW85KJKd+y6US7WpWTEuzk=,iv:5Hiz/zN9t+zWqXcknewB9CBdVkPgn+TTFAu4yeabV3Q=,tag:nOzpQPYM0RIRt4MVSPb1bA==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNUVabzNFTnJmTHhUdm56
            WFRqWGRZT0FlQUZTUWdEM2xCZ1F4c2c1VkU0CnRNTnJtcE1iYXNuZG9BazJRbk9a
            YmpZYWxKeCtJSys3LzNEYmQyT2N4VkkKLS0tIGVzUkNsOVBBdHRIVE5VSHN4ODVy
            d1FobkFZb2xmLzRiNTJVRWpjaGRydUkKaDQlTAe5+JXw99tyEL56q4BYHjF0fQwR
            ib2GIEd7MGKdDDtplQSJ8LoligNjN8CTtmlFfo3ro8yI2JMQ/3en1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:LCp2z5euiBN1jFLu2Yt4bPE166DBfQVmoNIiGGXcp+kI2jeqNAD49CkNgJwdMtWBKLn/q2LOUfqkE7fFaKRmmbvOiM+jtengU1ck4FQkaubkUuVeEKUpnKU+tLs+3MVumKXD2X2+FB8h2anQgugGv13qah05PJBaaGNJPW2Eplg=,iv:I7n0IY5dyiL5OfdJMpkCftGBlHbMwOaxT6yrUkCGazE=,tag:EOMPTQwFRrGMF9G9qYBEQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
