services:
  reverse-proxy:
    image: traefik
    command: 
      - "--accesslog"
      - "--accesslog.filePath=/logs/access.log"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.middlewares=crowdsec@file"
      - "--providers.file.filename=/traefik-dynamic-conf.yaml"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=porkbun"
      - "--certificatesresolvers.letsencrypt.acme.email=david@d-f.dev"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--experimental.plugins.crowdsec-bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.crowdsec-bouncer.version=v1.4.0"
      - "--experimental.plugins.shorty.moduleName=github.com/Spakl-io/shorty"
      - "--experimental.plugins.shorty.version=v1.0.1"
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - crowdsec
    volumes:
      - ../logs/traefik/:/logs/
      - "./traefik-dynamic-conf.yaml:/traefik-dynamic-conf.yaml"
      - "./certs/acme.json:/acme.json"
    environment:
      - CROWDSEC_API_KEY
      - PORKBUN_API_KEY
      - PORKBUN_SECRET_API_KEY
