apiVersion: ENC[AES256_GCM,data:M7k=,iv:1SW3g47mNJzWgf8nvEjI2ODytscFr44sQpkblea9Q/U=,tag:7dJIdUBUbu2D8T+AOnFo+g==,type:str]
kind: ENC[AES256_GCM,data:hCNW373j,iv:tB6SQyhBYZccUCiqyz3uY2gUBZIUG36Xd/f6udm/saE=,tag:20yPJ3Ky3odb9Zfg+FBKYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rK+bnxVzFsa6QtJcpME=,iv:QKD86vGMndApqZQ4Rz1seMg3oTlBPjsjvFiDbEkOYh8=,tag:OSYYPse4mOTvGMj+Ry9pTg==,type:str]
    namespace: ENC[AES256_GCM,data:nKYFRm7J,iv:lPI4ocH8TE6P2eFHQEFgn8mQQDls1lXvdbcPtfVh13E=,tag:gZZcDbjZ1C/4gI+YHZYemg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:sPui/M4vEA==,iv:EeH1KVS/dj3UIEDiykUtdpwGdvLzD70I6zDTp9hAX2s=,tag:nKN31Xxyx15jBzD2BY97Qw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:Zv1tXCaoXQ==,iv:cLpx7YlGJ0JVbRim40G6zPnmqwau6UCuOSlfvBoaoEk=,tag:BQ+6cdACa/tAVxmcSg2iRQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:rfvtru5T,iv:0j5a8dAmCOJOQO1rY/NObt5EQvGOCWY05LUnXcCeRrQ=,tag:YJn/yfz4HZcOScUjw6T8zA==,type:str]
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:1hWrmmqbHm3v,iv:2L7BsLJ2F0Lpom8U+ciaMvXBJXXWOJI8fe7aoX/Uxck=,tag:f34EUINvDd8xgIJiGgaIxQ==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:mLbjjHlXPYvi,iv:Qgzj4S8h0TLIi141csbVtY/WsUNcM3y9Gn1MI/UjHjg=,tag:MVU/VaPhZju9h4v1SoXE0Q==,type:str]
    CROWDSEC_API_KEY: ENC[AES256_GCM,data:0qffWGTvsYFe,iv:1CExHelLYueJhtzna21afqwQWC8g1/G4QEvluKL8U1k=,tag:LZPWzY090HwQb+dVwytgZQ==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNVVkZmRacFc0S3lTOEor
            NXhaMGFIZ2lORWJSSnVxVE1ZVk9ZMzVnNkQ0CmdSUnZISytKbUVxVG9iNUlleUpv
            TzgwbXF0WC81MHhMZ3pQY1JVVDBOaUEKLS0tIENva0I4aGdUVThDS2tXQXRTWmVB
            YzFsME1CZEdNYTF6bDRkZ3h2TXp4YzQKwThJC5jiVbvISht22aAqmugqumL0SPwx
            3PdO7Z9QvZ6phSMLS6E4ZMTkABJgAf55nFB1y/uy2xg2uowgCB1Z6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:43:49Z"
    mac: ENC[AES256_GCM,data:misQapMLkXHtX5AJrVoNFWDgGUzfpf5/gMxhSuH0fvxQ3w2M72RSd3ErkGIrURl+xtvCpvFWuXU0cQKP1nhRz+QIaiGLAhSgu0aBLsXBLB4KtP20zztNMXo0B0djHT6Yz3un1HKckQBfbbGfmMrswAq4KhKWigkrE0wb2Kh8NFA=,iv:tPwOKARBw6ptoXudF1/x3TA2GmxTRrRyqV90HNbSGaM=,tag:0HO0iW7diyfssI6IcrjW6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
