apiVersion: ENC[AES256_GCM,data:10w=,iv:XquFVBq7mLugFv/qFc6dW05TRoEO8ABmzmuqFCdRz8A=,tag:/WlEXBPtETPmk/O4RulNNQ==,type:str]
kind: ENC[AES256_GCM,data:c3jTQ57G,iv:q/4dNiwzurKyzT9M3kybRie+WbhXOzWRnzdrIUqKHGs=,tag:D5Ofgfj7yezt+xfeGaColg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h8bGfLHWwu0YK/fvTvY=,iv:3/vdw6PLfnQS7T7UYnZ0XZcJdwtnPiHIp0fltX7L75s=,tag:twyGuCpKba4gnpOs4c0LsA==,type:str]
    namespace: ENC[AES256_GCM,data:IV9ILdOd,iv:bRtOt92IPpnwAffI88hYKc7hZLNsKMxyy2ARUM4n98Q=,tag:k2b1wfVYiQPlg5liR3/Lkg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:dEeo7HYV1A==,iv:AiiGLAv66qDJkCI9O59OkHPdm+PFYf30lBS7UrXZ4so=,tag:Yo3rkflyRi7/GR1BuaIo8g==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:P0QA2CbYXA==,iv:bVt3cvZQPQTZXx3sLSnjkQOJ5BYKjHUi2z4uiWiH4r8=,tag:K2je90DGtlfHq4auX+vFUw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:3gB4IiVn,iv:TCacCJpEGprD0XZHEMR54U4GwFnZ3kipQGwUoAIj4Bo=,tag:0Zhx7QkGF8j/69HF9AzpRg==,type:str]
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:jnzn0+zNuEQ00RHmUSGU2sZNYMh6dfMSei948v2T/PLADvvlu16I4ybIHJKpgk1ztl9gZ58HxrY3bkxRWSClMS5lwz4=,iv:7HRtY7fjhZsujxEZuMYOMPPDqNYch/EZ4dqFJsQBcdg=,tag:4zCu6ekV3yT6Y6egKOmhRQ==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:cmObl49BDf7ukliPqJp77oquZAjTYHMDmm4zLNZXBNFyha9CnPhOhqR2o1l1342BWKLZQuLWOQuXNpSMP7C01C2umis=,iv:dq3xL+75cZKyFpWh/zkucHs7PtsG5fPJmtq71sFUnUU=,tag:LLB7U7ZKLBErQslF3cSObA==,type:str]
    CROWDSEC_API_KEY: ENC[AES256_GCM,data:3AfZfpmbYNtYGC7jsf9brH5Of3oomcLNcJ+yTOuuxIBtE66ZsahfWEsYDQ==,iv:zWyxSMTPFk92tOdzePk4yckgunOEwPAenNql6WSekSU=,tag:ZKVq9BKo9MrjGVyfgcmvXg==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN3dZZzBjLzU4ZVZEM3pB
            VlNpZUtBQ3pRT3lac3ZGNzFUYmxjOXF6VjFnCndKU1VNYklMK3FPOGErcmR2N0xT
            cE56Nmd4Wkpadmh2OTZFcUdhb2wrVUUKLS0tIFlzcGFlSGo4d1F5VTJKVm9YRFVK
            OG9ZaFRFNEVBM2FZTk84aUtacmZKMVEKryFa4zpPP/snDS4uXgi8428ohYzPEjmn
            ZEH/55Y9UNV7zlHuwD4RoSpoy7X6cnqVsXHZYEFjo04kB8agj8q2pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T02:00:28Z"
    mac: ENC[AES256_GCM,data:DBmHqVwBhv/qayPGkmtR+Jr0Bq2IvX69S0kSD0bctmf89+dw7cPZUl/fROPnFqjYaKvvVWR/LsBQr+C3Hd6mZrO5Mb1MzOF+OSRuivDnIEzbVa19PQsfYAPcP48JLacWtED462fjoRT4sUc++0jsNZ+r4SEWOTx2abWbsKr82+0=,iv:lIyvojtuev6b4/z5HRNRYLY9M8ropWKnBRs1Fm1iBfc=,tag:jhO+Wpo5yHaRpdP0R4FHyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
