apiVersion: ENC[AES256_GCM,data:Vek=,iv:DZ5PtrK0IL4JFwlasJyN6QMYwgCy1HDzNYRIxBBv5SE=,tag:/fqzvMwhlgyX8zsm4lgP9A==,type:str]
kind: ENC[AES256_GCM,data:zGOsqmal,iv:cISLuklwH5Tr6+pIjo/BCMB/M9kdJy35Ao+7+kaSAd8=,tag:nCOe3PxkTTquk0ezVb0A+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CR6FyLsGFdQHNqS9S4A=,iv:buJRxMxubf1g06fI3P0eSG0imPvVEw25rizoEinaJmk=,tag:CDb4BwMIBmTBCWaFAv6K7w==,type:str]
    namespace: ENC[AES256_GCM,data:zUoIuP+i,iv:0oi6ex5iMe0aTrplUowTy7H0Gvg505xS6gdRLX/E/fE=,tag:IPSBmilT5S3MBfzWwLEzOQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:kYFQcmZ97g==,iv:WTAtlXDoS8AsXVngn+qKzAZcWpO3dw7c+V2zj/ajY3M=,tag:oGo/QjEkcqSqO4yvENh9jA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:DrczT7LA0w==,iv:IijrDokcqoNGUo4fF711xja77TI+xSZpqM7VLpVC42I=,tag:YEs+6XNGLLi3qFEemzlp+g==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:rGV8yfiw,iv:RMj77nZHWmob1IOMorNKBJ+NN3L62C7jEo5gDQqYkK4=,tag:HomVlLEwwTs9/Nxi6VDdPg==,type:str]
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:EBhRYn13lJfcZycyVkBUUrjrUr2cMS3q5RtxC/GpTVVbkQEURW1BKkwSAIv19MYdTjmWUsDoLfqnS5RRn+O6MpLJn+g=,iv:kxynrop/4UaO7cOWhTlF7Pa9ic18stw5J1YyOW5yx3A=,tag:OXMxlg5AVufY3TyjQgnh4Q==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:JJQL4YlfXKjrlR9EsGCzXdF6zbxPNSZ23DLXVQXtuUF2ZwnGFOTSWg8J+b6jpuydWsBWnIfSAB6P5+hr2ZmTqGSFXXQ=,iv:AJB+fL+kKmYLANbt6Kz//zQ+SixksKQEpExMKt0FcCk=,tag:75mSsQ9/bHHJxelttBlcXA==,type:str]
    CROWDSEC_API_KEY: ENC[AES256_GCM,data:oEFgE+yHAk3dmCLJUaX7MTN5CqtQTXmav+JwaECwNT70Uw06/ngUPWFzsg==,iv:fbHHDUwZei4qixsMKLItZEeGIo4GQJBOaseKyMrbkqQ=,tag:VL6qfB0T9IefaPWTWQXQyA==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ2tOVmplWkNWZDZGYUFz
            NDE0aG1vaDQwVmRPbUZpK0UrS0lvNDJoRG04CmV3MzdDOGtBQ2pZd0N0eFl1K1Jy
            UUMzT2R3U0h5Q1drTDdNY0MyT21WZ28KLS0tIHpibk55K1ptMlppaHRPL1p5Smp2
            Tm9CSDduU2ZEVTRMcUo2cnIxbTlUSncKKwQMS5U1sNMCyACpFXAOwHwl4T6MpntT
            Qx4KVuPPk2zQlNU2PdW2VpirIVgfCMW9+x3ly6QCxkwzo/MSmHzTRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:pNvvtCCijXsupCsuj6NEsrs6430iH9X7kQYiDUZ8djE39SrCW8edpeOsR/UAZuOKcpLzaS0ss6YA4AGn12U2MPnolQlgRz3UW7zfjOs9gU/uq+qUP/rzBkiE7omPfpp+xK+ozKXLdGhCdaZs8I/chq9atek22s8sIu65lE3+wRA=,iv:Htl76mHb4n8FmhfY2OA4Gmc2GlBz/s3SPQvbGQZCGKY=,tag:egGI3Wo1ZFFNu/Se6e6B9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
