apiVersion: ENC[AES256_GCM,data:+1g=,iv:JFo+UM+MLxxb0x3eOK6V7+61NSXnm4ekUQAyzyVMLJM=,tag:LrlHa0bA/agST1uupZaJCg==,type:str]
kind: ENC[AES256_GCM,data:Xi9YGLF2,iv:uRqt9JwnYGa3a5E/v/RuSWE51kmktC7QZ9BydqlfqVI=,tag:h/23uay1Tt+31gUa+VILlA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BJscsOvhmzmtOBcOBG2ffQ==,iv:pEG8FK4OaHynv8CKG4x6amVfwhnz4jn4ElOpmQs3l7E=,tag:G9n4xMFkpiJoTWWd0oBrNA==,type:str]
    namespace: ENC[AES256_GCM,data:lUPnfrMI,iv:EN9XqqgHxCEyrgZMQUG9zrwLO8GKQ32YHE4m277eiR0=,tag:rECczfPxa7/6+A9fFspHbw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:i6GOSUG0kqSy,iv:HasaZP7Il3o/77qBPtcRq1nUTmDSvRMwbGmZWR2Chww=,tag:6yP1tW3ib/Hgtgavvve59Q==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:/EyB4JJMsg==,iv:S2NwKjyruC7cjgfWRy7ojLeTflfOjm3IMgr2J4oHX9g=,tag:KIqRzlRC7WCQdfpYUBD6EA==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:vHdH5HAf,iv:qMvFSROihEvLzHKzou0MRz/rsYsXxkCivj8E4jWPhiY=,tag:hiAz9nAExbBglfQZh8ugDg==,type:str]
type: ENC[AES256_GCM,data:FFZYPFMi,iv:ZZrG+5AF7CNZTaL1CbcutnrCLYjWDCcRi2JspNyUjME=,tag:faQEN49QBx7aQL+2LlLBRQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:7aAdIOqkrDOkp2rXpPlHrubI/xJyrvx8bXdYIRqDZ/7vfoR9Wl1eHdoWTHyShsl7,iv:vNJ9rz0ZCWHYzKMa1yu3blCY0wwIlDCmG7qjyU5dKAQ=,tag:CfBMNCR6JwUZ2U2gJobjww==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UmU0RjU2Zmt6RFhzTmpl
            ejRxWURzRUJNNzltdzdPNTMxSCtQQXNkd0RjCmU4anJkNjZHNXRxRXF0bDAzRzV0
            V2hwMm5VREppZXpERTA3d2locWVObHcKLS0tIFRpclZUaTlJai9zMDVObEY5MTJy
            ZWRkMkhHY3R2OTR3WWFvYmZ5c0EyTVkKXPchHMaz3O/LLBzZLZKKsniHUsI0s2Oa
            0HrRmoE4rvrLgrHnwIsC66XscHZajMSa/tLCt1erxhC1IvdIM8b5tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:ZKi09Eih7nWhnWmz350H1tYirU1PItDbKvALQ0CEKnEYIav+Qx7JBRw3yN/ih27GCJAdyvYV6MBM0Zsq2yKt/XuhWpkinaO067Nvaz1Xodk+83UqQvf/MlRdgKnsHimqcPSgwsqIVBVPl7je5pOE3trw62v3Ek1FHH6r0GWAffA=,iv:rZs1MwypJ67LV214UsUAMYxy9XF8yp8tikXm3k7s4Y4=,tag:0VDjcwHMfqlMxe9yxgXkUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
