apiVersion: ENC[AES256_GCM,data:P1Y=,iv:QXX2cEfgHZvEaxmlY2UFkqtlHlTrAdNGq0E7DFlTKqw=,tag:/LkN1rPFIjal8CEEQr/B4A==,type:str]
kind: ENC[AES256_GCM,data:GbnQE2FO,iv:PVL3thL4NTaG82mSJZBFVDQ46j2LxwX6g13QsiUjZLA=,tag:UjFeRV4MQLXxtzhakqytYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e5yfPMak+kEaP2n69SuUpg==,iv:EyrrYhXCmvqPcIfhmbOUs7cMiANuxeq56BiLk7iU33E=,tag:lGlj6rH/uxYy3G1TJVfy5w==,type:str]
    namespace: ENC[AES256_GCM,data:euMZCG4d,iv:pDctHyNEvN3p1C3HunIxvexPkGS+jh25x2DH9qORq+U=,tag:/mffV2bxw5oIcHH0q2Sp3A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:zJCihdVG7Mfc,iv:9nBH6wKEdNxv/OHeXQc07K7DsLLz7P+zGDm/ndCCkuo=,tag:x/SeD7QX2L1lDZqyLGmUAQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:1rfuxC5hUg==,iv:l4TEhPTE02AHA/deW4qc/CovJHBMCSZI3J5fsHkjnm0=,tag:UZT733i7AwTd/qwhjknVuw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:0uX4EMYE,iv:um0h3z5mU7pQ9O/4+Gm695cAs9OXBaL05FyR/5I3EuQ=,tag:PosWqAVcnhi4m+TGiFr5RA==,type:str]
type: ENC[AES256_GCM,data:uitXWUp2,iv:EZsFPotXbFCUWGcxOp4+1mdUYup5kH4rsW53plgN/BQ=,tag:l+hC6XlY4KNGpm6VCgUpmQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:RCTX8ejh/m1Uf38glxYZTEAvMAHvjTIksT2T7cMVigf76CRfcTAP/qDWTuSXWrUm,iv:QGquSq2GRztfeDzOHXa5kgQJZD8Fcc551t5g9FowZk8=,tag:QVns2ZUzsbFq6ivmuQqFfw==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUml3OGpML0ZNWWl4YWlV
            UnJ1cFg4UThTNVZRN0JwcmhMN29Vcm5DdTNFCi80TFVGOVpGQTJVWDFDVXQ2MC9q
            RHYvQWUzVkVBTGRwK3VZN1B0S0FKbTQKLS0tIGlaS2V5Q0p6UHpldkltZHdBSFlK
            MlRra1FvY0xBZFJlL0JSVFZpVEVYOXMK8QGXe5+mB5GMdgHPt9KP1n5csdUC1Ijn
            g1gjsSEtXAZES4oXXGdNTR16ODEJcuM9RMEsmcJKfMhY4sODM1r9oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:43:49Z"
    mac: ENC[AES256_GCM,data:rz43BNikzs9Hacu3F/IqJIDBqgNBJ8ft3T/DehkanSq4x/tU5GfItvc2zJAN2FfhpjNq230or/JbIqbpDX+DzDrJsGTflmj3kNkEwbK0tdWuX8xjfVpj3EZUmm9obiX7KXbN0Ji80v05+Yr33ZveqDBJ/Vcy7w8jy27m+nd52ak=,iv:di8waZtTdMhAgTtVRjyL/17KB1wBhwlLJBFW66OSo6w=,tag:ltGwg2OX0mjHHMSpfKDSlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
