apiVersion: ENC[AES256_GCM,data:xlc=,iv:2K4SwnTXOLTh0h9+0tU+0Lwp4O6LeiO42kdIHBHl79g=,tag:yBuTSK29i57cUVyxtBSehA==,type:str]
kind: ENC[AES256_GCM,data:hHva1pOj,iv:RffCBWnA/8f0rmnf/i7p8qaxw3fuFnom20fVnd2KALs=,tag:W1JrJOEcyL/zlNJf0vxKxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HaEPT5F02RW7krWspA==,iv:2gSsQP/Gv3zmOcsENfdhVNSDOselEjzWOu0xu8zE4cA=,tag:9J80ciGT5fLPK603hS1UXA==,type:str]
    namespace: ENC[AES256_GCM,data:C56F+MSh,iv:StpRTA2BQ6XLg4LIEr6y0DRJ6Qpdt1bJtqgnq+zjDSs=,tag:zHKxrQJzstn/74F1AUxkjA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:Q5cB9s3Z,iv:iSVsJpXOCLNo0y7XPMCc2BUz4BHeURsiNjCaJaQYklk=,tag:8xREj2so2zZEyie8qfCv/Q==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:QBwZg7s6,iv:ux4r2uxjHuV6d82oLE258E3WchtApSyovnBIfrP1k+U=,tag:CV2swBwy2XG9ERBGSs4FLw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:rxJdVqPs,iv:d3uNGX5NtYL5JBOiSk28U1dXq+gYkWmPLv7SWuIxdug=,tag:IEhON54TRpn5hl4vBwhNlw==,type:str]
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:ltH8Ix7Yk02wRYe/AaZU7Kr7rky5wLJpjD4ALbnSgqDGvHk=,iv:2yTTsTMX2/mrn6EC0mM8X2nPLGonpwGccTKN/aFhzpg=,tag:GQPQL01D6/LNhZO54S/pug==,type:str]
    #ENC[AES256_GCM,data:zEHf2EGnXQHFshY3huc8IVp2T9pAwTGV6wn5bzsEQW5/GSffyjFt5XWdsb/WF7ctIIQTI71U,iv:xyVsOflnnzRNRZXVGLTQLQQVhoeMfronzWSZ9sa8cMY=,tag:Ne7BXbdukIcCfWEpSniUKw==,type:comment]
    #ENC[AES256_GCM,data:B/cF0tpajYM11Zz75gm7xLqBsC2k7U5yLtuTJTOQhYsZtyp5BchzufEd,iv:PQ3IQ2NYHSWsh/X0u2XpusXYdrzzNbrI5dOaMKbChzk=,tag:yPtgskqbiEmy5+ijh7gcDQ==,type:comment]
#ENC[AES256_GCM,data:NPkXWXR0X7WljRjfzGIGabyWOk91ohJbFu1isX/aRoL1Xk/OkA2ImvlTgn3DMQ==,iv:r4W8MD5lse+qNZ+8O4iqT3ztTVJcFjKf1iRtb4KOE4Q=,tag:0k9vyBw7Obxv4d6d2DMqwQ==,type:comment]
#ENC[AES256_GCM,data:my9zjrfBhesSF6mDFc9e0bWakC/mAM+3A3e7gqdCjBmOPmygns46ZIxxLDe/3/aAUJlAvif1,iv:50Ux+SN5VPBm2cf+unMCKsRUKUYCbDMVl5zESM1XE2Y=,tag:L/hql2biS0H5W2CGX8hcHA==,type:comment]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S0h3K29udUE5MlMvWXho
            Q09qUkFNNlg5OG00cVpRZjc2N1pnV24xMDFBCitvLzA1V05KYUIrOHNsSmlJcXZk
            ZXdhNGxJMnloc2lrYkd5d1J4ZDMvekUKLS0tIHIxdzdNWlV3UERBWkZXUjk3RlZy
            UlEvc2JyU1ZhMjd4cEltMnl5cFhkTXMKZqbcaqTUIVun+Y9uilorYshRFpGxclv6
            cjNnwnbg08hisDgG1d4A+BlzGi3Ubxw52sK6EXMMC/nvvLky7nIagw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:43:49Z"
    mac: ENC[AES256_GCM,data:3bF+MmvFOqFvUa2XpaKSlQ6c9aeuaXEpjAM5p6KUhYSvZrIxrr1w0WQmnmLUAZ/AEXzgLSGVLszBEtbeUj4RKV/lAq7E8bAxN7cI+Kllf2kpIWEBWSjKv85bcXHDVOm+F/3Wn/RnChfG3MAb5qtk1gjLZVy0sqM2QNE9H8qrrzY=,iv:MCQ2ZeIqJc6r+/9O3CqbtYelmIJy3LOGs5pb811Rcr8=,tag:rqJlQ/nUxQ2kqvCY+eR49w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
