apiVersion: ENC[AES256_GCM,data:zIE=,iv:SI8Zr0/b0tf0zN36tD9x4S1ometU2f7mj0/q0BxAtXw=,tag:EQjQR4sNRtyViq6r06I1aw==,type:str]
kind: ENC[AES256_GCM,data:181aC5r3,iv:dM+8sCFKP1/rjd4xzIA4HPVkX4U6WI8eCVu2xiFhs2g=,tag:UGr3o6JJ/Mi1PKnOstfmFg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pB29EAVPwzXaG+XySw==,iv:y2CGu0awrsG+EnUTZUd9X5lS3Wp7eUQtzWqKm2xhbVU=,tag:/BHUtcLfpRD91nBZVi7G2A==,type:str]
    namespace: ENC[AES256_GCM,data:SMNj/BLw,iv:ZgF2ZhRIh5/ed6UQ1pA/16utIEQqQo+3zkOVM078aCI=,tag:HVKODzGlA+mKqlYJ9tc0Iw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:+4ao0RVg,iv:n8XwQlkE3LOTTSuHWnekS3PgGwLLsVvFOUcWNP3mabI=,tag:nXgC6R7W4PAtIEMRAPFu6w==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:X9BugRXD,iv:W4t9dovrp79PwihFjU6nRlfVY9xTcowIpINWJhDCJEY=,tag:jolMVAADwkX3hrXI/eEq6Q==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:WxmMmLVf,iv:fPTR+Fl/eomPCX8zjEFXELC/kmJoEy96f7YXni0vjk8=,tag:bc4k/xSkTa7RhuLqaiipoA==,type:str]
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:H+LQSCPsDo817dtPPtWUnFU5CVxILihfnATn3ACRQGrlTRA=,iv:/8fY0Mp49tAI7/CzC4GN+5dUv2IBi4Ht4UtKy1Ld0u0=,tag:ztP8+f6IGF7cUOd5h0CNjg==,type:str]
    #ENC[AES256_GCM,data:R04Y0nrqUounPEef2j4L8jtQXWbaF213cRCU/pNirz5epna3xcEBx5NH1UT9Uj8EpYmRp/ie,iv:/gDwuw8HBDJIB4OLJnl2NUh62HjcjCq1fQ4WKpKQtuw=,tag:1huAa9TA0c4V/h0NZBL48g==,type:comment]
    #ENC[AES256_GCM,data:4iG7w3o7UXFM2M6nbK4OMyZFPrzIsFJ6VKuwW263aCg9XTIBtVE50t9V,iv:A2nyRtfIBv8jt4pCEYy+3ILRuIE84e6JR9uGXemLLK8=,tag:lczoUXbrLmKdrCt+nubP3w==,type:comment]
#ENC[AES256_GCM,data:/eC985g9ugWCQQXEAozLrT8mHmttvlwkgMmYaTUZ+NjAsidpqKB6OOO1uxPpfQ==,iv:U8oQCa4Us4Cku+J0/jC8FDV32v7CCAVxNiorPKZ+bvY=,tag:kNZbKj3R1Ck3IzE+OA24Hw==,type:comment]
#ENC[AES256_GCM,data:9RDLzDRuhekbG2TP83uaWLz4Ir1Crfx1gajIGJM+CI3U1Ij1fZHYaCAa9BqbEvX41OOQ9Q8X,iv:l2SsktFmAwaHbTrUiVZKmNwQMdgAh50d5mowm1JIxz4=,tag:wZAEbVX9V+KLKENjUKFwTw==,type:comment]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcDJvdmh1NUVVNFBNelRr
            ZDFMU09Qdi90S3JFYWxjU2FQZ3lCd2swNHkwCnBjT05RUkhTUTVhS3Q3OG12S09F
            enBUT1JsNG5QYXVzY2FPd0lsMkJxREUKLS0tIDhRY3Q2MlRjVkl3YTFGSXpleFpE
            b1ZHY1dINXh1T0lDZnU0T2lJOTlMaWMK8btPq0+oY4JVCdlvW6C+1gWHxVmPrffL
            vGEiGOSjcnLvzV+LBFOtiioXmX4mDUhYaK3eE9o+m+8srQoZuTHmGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:EzNv2ghQy5AqSnfs2K5SxEj1S4pPN7Xxa80jliLfQNVh7YK7Ze7lKsbAr0EKxUasZJiCyYd8S/k2msRs9bFdn1JOhaCiOtt0QuEl5aJ4GGu5mYbVq0oAI1OehzXKqk2BksS+fuKCLofOWF3JF/CTijuBxeyc1C1UYJS5R/5gce8=,iv:JwjlvZz+IUnsqxK7WOThFWNQpEG2tCU8XKgDpQ/kmi4=,tag:Iy6YceYIt4A4FdC+ylTV8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
