apiVersion: ENC[AES256_GCM,data:nMQ=,iv:2POyszr0ShJSTwvOZwGCnKtxDNuou7lQZ7YnCgGIMn4=,tag:WsBuJV9O57DWiUsxEbt/GA==,type:str]
kind: ENC[AES256_GCM,data:yunrR/Uf,iv:Cvcj3w4A2WhymsfXhJNm1+h66XIjYsOadBMtLGwbZUM=,tag:MHXG2jH+3qGDyvco2PAPOQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pI2nAxnZIx3V2iQCDg==,iv:pFveEXmQ0EjSmGmqOlnSBZ7d+Esqt4d0z8oV0bxqUP0=,tag:Aiw0X30Cw3Y/rcO0eDDu7g==,type:str]
    namespace: ENC[AES256_GCM,data:sJy8aPyn,iv:+yDKjWtvrJUNBXY4Js/fagcqiB1OuUaotVnsR9SD0R4=,tag:yfNJfcEikf1ICXj0wDAzZA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:t0IFAL2e,iv:k+W3aYzByZjWGWxhnUhULcsbEbwqImjWvBg9RkmuHAk=,tag:h/kTY0pNec9B+56UpTU2oA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:40Qy5O9v,iv:RWMqU2lUX6MT5xzv5ZpTlwX4Nv/GR73HGnBBkgDyPu0=,tag:CfgA/T7CouiTMNzxiXnP5A==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:0jK1K0TX,iv:Q/49PO2W3ECTR+fiNSqUG/+0w0xtHncKXpLcAjs9sGY=,tag:xcbAQqrDZp9LVRUq/IYQ9Q==,type:str]
stringData:
    SMTP_PASSWORD: ENC[AES256_GCM,data:pd8UFAkH0e5vGZdGOZjWZSH9zEQBQ7ucBYoYnt4uIKLKjAc=,iv:+hAOXc1kVKCGXtTxf7OTtXi6o9DwsP6IW8ei+DDu+/M=,tag:AMbzjZP7RCjxIGiczsjv4w==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:hshW8l20Vgj6EZ5UJTMdczzZINtKFTvTVNAMkYkqkzWcQ91R4HSZkg==,iv:QIMQppurPxciOjfoeWR91koi74gGby7YkqtEJDS3iFE=,tag:HalT6nPHW4DO1fboNyxe6g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:E/0RAy2S80JElbuxEyNLcebHMHtdd6nqJqhxBq0aulFSyHdCAKg6KVYfSj3MKlQkDN3+d0V2vebjx60xn5pQp92gMfeOnBaDyxnKXDlIkNYpDGb8fV4xfkDLqFe+dOOXkt+C11NbLP/hKmLwRLQV96y5ZeZErqv7URftUQfMuxA=,iv:3rI60mcRjo4/GkBH2gqoFHEugHZpawnp7/oAscY4so8=,tag:qiBaQw8UOCDn6+l1+o4MhA==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbzA2dWtKUVpVTk83RkU1
            UUt2WXp6MTFmU1A2dEFrUmhHeEszaDNsQjJnCmpsRzJNQWhSVzNZTVN2VEZLSGVU
            NzZ4OW1HdEJFanZzc3dTa1NPUG0xcGcKLS0tIGNoZWJFVWNiQjZhdFFlUWlWYkd5
            NmVVdWpsbTNudktSVjBmVnFmMUNSNzAKeCm2euBqLOMt5efpuISDTjmbESmr3zez
            XNN6WILJJHM2NguUKE5GsSjTqT5MzzVuCdjo+1u4TPMa0+R6+O38Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T00:55:53Z"
    mac: ENC[AES256_GCM,data:PcvBUd9KEzFLfiYU45EIWK6LvoZYpNrGl199cbrwTvn+hEUNpIhdjMu7ngqa092YIs92J2SQdMZjXFsMicxQlSK8ZVcMjvc/cnfWvco0rm/AlvMQEDzxHJVyH3j5x9m5izH+QB/YYlbA1HUB3Ygbo/kPrBN6Xmd5CcIVLNrilZo=,iv:UoeYWJ/hjygrPWzqag14VY2zVd9j6NGkcy5R5klyu80=,tag:SF47dWd8BAD8gQVHH1NO2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
