services:
  plant-it:
    image: msdeluise/plant-it-server:latest
    env_file: server.env
    depends_on:
      - plant-it-db
      - plant-it-redis
    restart: unless-stopped
    volumes:
      - "../data/plant-it/upload-dir:/upload-dir"
    labels:
      - docker-volume-backup.stop-during-backup=true

  plant-it-db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: server.env
    volumes:
      - "../data/plant-it/db:/var/lib/mysql"
    labels:
      - docker-volume-backup.stop-during-backup=true

  plant-it-redis:
    image: redis:7.2.1
    restart: unless-stopped
    volumes:
      - plant-it-redisdata:/data

volumes:
  plant-it-redisdata:
