apiVersion: ENC[AES256_GCM,data:lDM=,iv:r07ANgkvgmFAPpM2Ks/PE44jCkWVYqk2ImqoBNjezEA=,tag:Jh/0zcogl+4tyu9Rohk2hQ==,type:str]
kind: ENC[AES256_GCM,data:2XcHvukz,iv:cr2wP09Dt1CoAaRCTp5R9QYPt0HvrnvRfunncTcFHJs=,tag:RSvUphBW1e0HpitLo2K1yw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZaH0ahvkAkzuZQ0FbccI,iv:pwNKl+hTxfs3g5MqJZAJKNly7VNXhveQ6eAfPFAu77A=,tag:MFGyTfpGuAQmrgkfdRzaTA==,type:str]
    namespace: ENC[AES256_GCM,data:+glAiqA4,iv:JCbFUZjMFFfINRpWNByv0XT0m0XN11LQlQ9F5xALnRw=,tag:yDR/+EOuTDOktbwj5h71pg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:q6Am20c7j8k=,iv:D4ma7bx6VQAWJMKGSmAxZN36JfBYIWBTZPgQajU+wUw=,tag:hHEdE0ZOEZG0XyF+W2ZAqg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:t9iCFHsW,iv:54LF4LZBWzeV5KpJ/6IoA7NrYqLjRAdhc2waPYPiGmA=,tag:cS5gIzrFQHHpcGWDP0vHfQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:13vyv+j9,iv:rJ8ZXHtT9eoX4lisIUTgs8J4fcHIYdorOQcpdZvdiRU=,tag:7JQH3LBk39GJJWhOXwzH0w==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:vplTEgO6NMQTzZ7xFgp1SlKhXExQ8xXC/1EglLF9P3EjK7hkF83cwR9zdmzK,iv:JWPIb73mwXdWnLCAiXgtnBmMIcVu38B30gN8GEL41Ks=,tag:NlMq0sJK5+3mMuDIXBvsJg==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c1gxNUVwZCtDNEZ2MnlX
            RUxUa0d6OEhJSkJXa2U1Vlh4cWtNUWpVNzJrCm9NVVBwNEtuSVRhb1lyY3lQb21T
            OHlJUVVGYzNmbTFqNVYwTjk1eTg0NVEKLS0tIERKZU5VUnVKY3ZYOURDZGgzUmJv
            bkFkY005L1VRSzlxN1dVK0dvUXJOWk0KhPx6zt/f7xM5t/Nzafz52+821eIAK3Lk
            HDbWyzuRuGbwdPdHIPb99Ni0BTNoFkg2MPK50ghkcm8EvNsPrdKGXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:KZOXnsZg+ju39qk0EPDHKw4JGuSHAYLcVQsyFFGE3t41VSVQNcb+7P44Gz83d9TihdBf2PhNapW/e4FksqLmOnLUTp6LrBX9nmKW/n2xCNBmwxZvHiAS3zr/6QuffRjzen1PUVYDYLqgqxozEKrzUnDnFj9joGipMFJEG4j8+Tc=,iv:zyVgDk09P9yIcFuwu8puNbhh5ya/CreSBOZ8n12xY80=,tag:dhPgLcX2RjzKwH7j3Co1Xw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
