apiVersion: ENC[AES256_GCM,data:cRM=,iv:BfHucasLTkHUYCwcUxmepEDR42r8pf1GXgWlcepMAbc=,tag:OVBw0Y73d8oopxagLlenqw==,type:str]
kind: ENC[AES256_GCM,data:2oYkbVq5,iv:danrRk6OdM0y7V33ByvB0SMtaO1OKaftpwxfH9YVKmk=,tag:iQMgPFF+rWjfcfRnWt2O7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Cecq3FfjNuafmKyh0SUR,iv:TJQf3Ti4O3a065+VYnO+Tp890yF06DDHCZhEk3ZcqpQ=,tag:EiJneJnhNmH2/Je8tgbZyw==,type:str]
    namespace: ENC[AES256_GCM,data:HdmyXt8t,iv:MO2oc54NMkwuwi0EhVnqkQntf0OniGwvoco/P/41yuQ=,tag:TipAAAtWncdkZMHF/Buldg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:imcD4kfgP0g=,iv:Nvy5mMyaqQtgkO0K1qyetryTf25Kw9Y7pHh0zM0JUzk=,tag:aqN+9Kz1/lzsvukdAZBYiA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:z/jEga7a,iv:s5DrJ/VimgUVXd/xoRzE/gWRXepHSZqhZdeFGrZrnN0=,tag:YCdEKfg/LBybd+NBm42tEQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:DHPEy+wc,iv:wX7YArFkSgsllrd71cvkZL9F0ID2M8fGzAQEiOpqFEQ=,tag:nYNeXK8eYl0b+07Tlms3Tw==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:FsIIGLiQ/EiJUfn56dMPvFwrxBkg9F7svpabhh2wA7Ap+vC9qPMOYCRjvGNP,iv:aRexgPmKwPFJiD6tcTTPXNQeJVDqVVtI0613XdrWC7Y=,tag:oM+lea/MA3QFYY8YYqzPcQ==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTzdSNTJyQ0twbWhBUTBk
            cVBnWHpGd2hpc2FLQ09OOTM0c3VZWDZkMVNjClpTZE4xVGEzaFZvRnhJMnYzWjRQ
            QVJJdVZkOVRzZUx4ai9Dd0lKQTcyN3cKLS0tIDNaV0o4dWdRYW5NQlB5VzJCZTIr
            K1FaaEtRRzhmWWVuV2taSTRHMHljeFEK9CisJGnJBY/yejNhYD+FgvqLBpK9fCT9
            7rfz6sTY1CF5xqmP6J8SMEYmtinGE0/w7aZG0s3mvXrFMrLOu+vEMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:43:49Z"
    mac: ENC[AES256_GCM,data:/7h7v7sZzvFIrr91itlonYdGUIjr/e9j6uVCedg85R/VZwuqDKKP/1UT9my4pRUmihsEQxCdjabZH1tPHRfzhKzUdGVJM4My/gy6nwXREWuRsLXc2DF544yPKfOeWFS3Q/pG75Qgd4ItMpTy3p0XyivnUpdFiWQkmvUA0FvM25I=,iv:xzYVUTDEsjW772buMHBjzoBzdoASkPkYNRh7GLisqgw=,tag:Gd+NU/WJDDGoNxeLotxEcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
