apiVersion: v1
kind: Secret
metadata:
  name: plant-it-secret
  namespace: server
  labels:
    app.kubernetes.io/name: plant-it
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: server
stringData:
  JWT_SECRET: "change-me-jwt-secret"
  FLORACODEX_KEY: "change-me-floracodex-api-key"
