apiVersion: ENC[AES256_GCM,data:ejo=,iv:gZyfpEVMbwG7yIpyKaAJvLxQIxlV5CJC47HEsq2oN2M=,tag:X6wg3MxAlTWTmF/QRBR1GA==,type:str]
kind: ENC[AES256_GCM,data:WTHQ2T+T,iv:IO+Ly/k1qRwe0FeZKhS8YVEMttMfTc6Lm3Jz/IFN1fw=,tag:hQjzAQppnpCXi4zUD4Uxgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W+u5lVS5U1Ov5uwRKIYdqhE=,iv:GIq40znSaZMh+zoIHUpwX5kzsr3wTcCMku7Xj0072Ro=,tag:EXAa+6hqvytKkYEl7ByYOA==,type:str]
    namespace: ENC[AES256_GCM,data:/vGcWWL7,iv:qD1NIKXm6rMeM1GxX2hxaoY6uAFQ7OeKPZmLHehe6zw=,tag:Ij71f31NfCTmJOML3aWmsw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:Tmmd1lMG07Bxrg==,iv:2/KJ33iPOWNKSHWSifYIaYsHu5fBj8PXKVSpmZzRZxk=,tag:6O1/2amiFJt9olE7PL9xtQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:uz0RDthbWZk=,iv:lmmxq+U352wgO13A8xb7kFQ4RrWop8+ic7m83CPzx4Q=,tag:Z2Xhk8RfZ+j9xnHzTm6wCA==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:duCmM+dA,iv:F6s4uhQ1rcJOf0Mlj5RjrHnfvZC8C073vL6ZfgbUkKo=,tag:TknSk0ZWmCcRr1Z/KPzDyg==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:C940q8/5aEpvgXRlI3qm3s0eVtdIDKA5z29IyTXUZyHpPyne/uSniV4x8m4=,iv:4U5yhH3K7g1EcNqVYXLP03SR3p6g/zWMkhXaIr+xJGU=,tag:hI+e1QXokIt0gaLn5ETtiA==,type:str]
    PAPERLESS_DB_PASSWORD: ENC[AES256_GCM,data:C6XjfA1Su7ZGbtd4kV4muNa+7WDygTlXZIAP0YIwcAy6oEtTxbqEDYcOAA==,iv:dBq/Y8QTFUDrAUQJZY+kgRWxR1Tm7OoXMvC16zKHZjw=,tag:irxXe4hWwlL0wYCiuIPsfw==,type:str]
    MEALIE_DB_PASSWORD: ENC[AES256_GCM,data:WzwNz/cwbCmJSBNkTgPiGjJgqMhjOS8tyOu65sPFrsoV0g2dTTFHe+clU/4=,iv:4nqr2wQDUFNZBdWfXO11tMRwOCwXi5rKuq9EPSFPZHw=,tag:avhpzlqpNFUFuvtdOKxNpw==,type:str]
    AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:BunCXO5qgeZ46iOcWdIn4kOtO0ma+J5BzQGvpPamFsiG/MhLDDvxPKznmCcverUuxg==,iv:muEhhcxa6G/sPU1abNTftlgd/BO1nSBdukkdKfFcGBM=,tag:7gLHfSufsddyV3EDzxOAvg==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaGo0bkFMVmZ1WnE2VXRG
            dmVXRTExYjFGUUMxeDZLYW91bVRCb3ppdFJJCjlwZGNnNEJXRzZaSEhwWXFtcCs2
            NXVZMDZzbGszQzRObXk4M2ZtMGorK2MKLS0tIC81WWVyWWVISk9tY1B0WUxHS3RB
            WXlidUM1clhDM2dLbm9aNlB5M2UwU1EKVR3rI2luVqfoef/+jm9PyXBmEQBMcXpc
            EQFlLeZh41NgJOEOBF2O4WhFnWKDYHlWUdOAKbGtFaXbpIi2E7IWUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T17:56:13Z"
    mac: ENC[AES256_GCM,data:rDevG+SdONfwz2wUL0pzUrMRLeWnKblfBO/nVPMBR/rdos96RB13FhHrelb+ey1e4+EdvRn8iOcQ2sbch0SXrjuvyDZ2EiIro+rO1gvQjb0bCG+JM1ADzWAoRVdFqejCIKtqU2+oZDrYUV5HiX2v1UmQufa1yQnkaLXpVeIdpDQ=,iv:aAuVCr1XQ/jsUL2vzPHVfrF5CgBulxRhrgK4bXJ7GD4=,tag:dCypmaN2U4vEYv6ONicXOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
