apiVersion: ENC[AES256_GCM,data:OcY=,iv:buAkezqMJq+p0Cvfr1bx6vqI1PnXA2KzyfBLuKy1sPQ=,tag:Y6cAsTsvRigkEJ4EJXFE5Q==,type:str]
kind: ENC[AES256_GCM,data:7ORpRLCL,iv:wqAOSzG3RQI9qOz1knKqjaNTAJ2XYOsmQ/H3ulA2EG4=,tag:qqPzKIP2fvk8i3A0cZHqFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CmHYqKZELGoGWdJDigA/Xdg=,iv:Qz9gmEvsJKP9Z4FJQU7uYNCluIwNziqSNhsHOWgkhms=,tag:aLkXlR3rGELsdsxhAVtg6Q==,type:str]
    namespace: ENC[AES256_GCM,data:3E4E8/6Y,iv:rJycFdv+znhUBpCTNBkWVUNDXHnwOGGOkDhefk/FRIg=,tag:7c7BBSBcvwQt07+r5l+M1Q==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:eLUKyGk/o5f8ZA==,iv:YhrRd9fSzDib/DuchWC+lqlQZwj57xfC7xVHmV89Hag=,tag:DgcSf0uSuYcbJkmfZvXJtA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:wVwb2pfQEzI=,iv:giT5m/JSUT0Zp4Miu81JCVw/6CwGThNWSdS4EmjQCGo=,tag:Vuwpj/H0t4rjNyI3T2PuUQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:rconPfxy,iv:+8beRJRic5rzCLf1YjErVWtwJYWDEaYa+luoIwMlRig=,tag:aB5nZuWRzrY5A/vchfFjkg==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rXwySitbyt1A/O+lwc4I3sk+qEG5/6WFRdrDTzAV0a8ighPtVCRdM2797UE=,iv:k2tc6nlgZ8Lsqd9mNZ9KXm21hAm8vkNSxreeBcW+h5o=,tag:NbZQ3f+eQMQBQcTr9wqUVw==,type:str]
    PAPERLESS_DB_PASSWORD: ENC[AES256_GCM,data:U0DcxwaXQCYAAKAidM13MGKXQZ1j0VLIGlZaNQYR74rDvGXbC5rk5jtESg==,iv:RmXGy64o6vYOtIsASVcPnWKBffOvECFO6wZliuJLD0o=,tag:i7VxxpvWmIaRba6IHnmE8A==,type:str]
    MEALIE_DB_PASSWORD: ENC[AES256_GCM,data:H6Wtpbk5Y/DibGUfIXAQdqPQAMSedAtlLEGJ5hJ6VVXqKag6V0g4oZCe+I4=,iv:1xCmveen/jOrK42lj5xG6AoYSSMsCGwf0W5T4kwd0VQ=,tag:wC3hfePVnx9Bhx7TBfAvog==,type:str]
    AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:sBwRu1fvQG2auJIhxbtCG02Uai79798wsRjNz9K6z0e6GaWKgfAHA44IPtyW5Lpu9w==,iv:lzVp85R+vIPAg+lcO2JYSTPfrSlcmpyAi7uuqr0jJbA=,tag:o7gsCdxtf5TY56EF5K3VYg==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc0ZXT01oN05BNklNdFln
            RWtjV1VabE10bjhwanIzdGxIdUF2bE9NQW4wCnE2aE5uTzFjdVpWRTJOekI0dGd3
            bkZXVmFZblp3VzVIUEJzWUxWckl3eTQKLS0tIHZRUjcyd0hwL1FWU0cvdVhZU1h0
            MlZyKzRxQlMrcnRhVWlWNHhYNThXREkKPVB86fWHkwQl18eCAddtR+1pDTxuesBI
            LAmxDlNmRokyO+TIrnARuPyLw58vuryxL0Au2eIjdXnJtKYwJSGIKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T00:55:53Z"
    mac: ENC[AES256_GCM,data:5dHKYlcpTdm1iN3IrPHvdn7xsd/NiEgDaj1c58zdVz2o075TTdzSswVkpOi3Yiy1hmYhM8jA4gJrVCWgUc9qtfgMbpGcYzEKxOV/docV06ij6kf0csertzgJl2fAUTi68X2tz4pCpFLhRBIgt3EwH/+IzN/0G2+m9xNSg2po70M=,iv:pSTUkTPKN510xYiSyQ/WXAbsHDBTZQDuA6xmRqz4ZmI=,tag:H7l6Jv+dsOxz8aNcYPGsxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
