apiVersion: ENC[AES256_GCM,data:LFw=,iv:rxCm3mwLXTYHXOnagMEiHIT/cPIOqQ9jq2hl91rwc18=,tag:6tvKRsUTB+Kb8lGoaSCEkQ==,type:str]
kind: ENC[AES256_GCM,data:rX8yJZzX,iv:YJZiYyL/2GJkz8DiHyuhBsBwh2rylY9keo0JlsFTzsA=,tag:C/4uRX4Ub6+NMgQuFuqbbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qP2YcmSGGwwu5hs0wS66EqE=,iv:tl//9ayvzKqoyOysZUynnJUzJeS1n2TXKY/J0uMnP2g=,tag:qxLrq5njAsjODtHYhO0+2w==,type:str]
    namespace: ENC[AES256_GCM,data:Y41RIk3a,iv:rkFjgVYZsKqoZgfLySDPrwezlz1WiO7n5KwZKy0aMio=,tag:oSHwh3wDPwJvXwaBYv2wdQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:sufJwGtBm74JNQ==,iv:LSsWVjvIi/SlwB+zehgBj6XpBvCRU2A08GFugCFeAFw=,tag:RUHBoRjuE+tl/uulSVbj7A==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:M0iwd4J6bHA=,iv:cP5jEB1SHeJF0Uc2VjD+lh9nUywtJrkNr5+G9FhLSFI=,tag:EGMWah523dudHJCY1xLSTA==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:fo6ioX7L,iv:Mw/1DAsDL5rKUQJtB42JnYuoiuxxVJzJ8V6a+9YzGsw=,tag:u3f89MtcvI/Kyi4ACSJ3Og==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:eUzJXwbye84eXWXcvoE22AXPiultTCq5iV71Vr53BnQPOypqQEXVa6PphqU=,iv:P2ooJo70kL20BXoBxi39FDMcL1oZtA3N8e9TvgMXbUM=,tag:7cFzp5XFiv2qsXkce8cgRg==,type:str]
    PAPERLESS_DB_PASSWORD: ENC[AES256_GCM,data:m/M36QhagrsGV50YY9wRiY3cROg4FSRNSrEAJEmb5PVByKAd8CUG6iiwXQ==,iv:28yj4HREuDOMdUwwt3EwTEbxBx41PBpHx+zNj6/1DjM=,tag:fovqVJH90S3wV9r911cUaA==,type:str]
    MEALIE_DB_PASSWORD: ENC[AES256_GCM,data:mES3PMV6HsM3TQcx7TcsZrffijUhuGRh2+b/KRORna0MLdqVQPd9rhkF2Hk=,iv:DVz5wG7XugRW9BWDXDs782+rvDIYpt9LZWsCrZ/CucM=,tag:1ShQBzGKAnpUu47ijkGS6g==,type:str]
    AUTHENTIK_DB_PASSWORD: ENC[AES256_GCM,data:UCaGm6ZMPS23k8h3itb9o8bq3pkq8O9YI/suvko79gzS6VP9WSYbX0Qah9EB5Fkt+A==,iv:dhWRUc6ixmev1k3657adcI4C4FJkTv1UVdX+jai1zLM=,tag:TTKXa7jw72OvTqh82bm2Uw==,type:str]
sops:
    age:
        - recipient: age1qhck7uvr0kywmqgkvzw68w9zj83fyhp4drjc73fdfr89g74utspskgfs50
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb3ZnUmNMTExPMWZjWVAx
            OEpnYmNsT2NROCtpbHU0d2RHYlY3TWdUdDJzCmxZeUd2WFliYkE2UHcrUERraDhU
            S1ViaXRaQ1dzQzk2QXlyRGN1cUJkVEEKLS0tIDN2SE90b1dZUTYvZmVBek1DRHZB
            VEU5M0lQOHd4YWhhQUQ5b1c0azZ1M28KDTzv3Mb+yasv1vRkbJ1UxtQHhs8ZVl5H
            6Hda3cP9DObmyulQzm5wBVIosbCKByoVDnIOdiwrO7dPHXn0fiugjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T02:00:28Z"
    mac: ENC[AES256_GCM,data:c5LhCfWkchKaz9cWOZuWca/IrYd0Mpf22M41CN6XNSRzKotqLfDISyET669k7VEB98LlDdDueSXUldz9C5zOa9m4BhnG0NYeyUlptprwnLF9J0BvD2AOitUm96K+PsWePhF7QqpHKyzSvZItFYJRRAvDjX/QqZ6iqj3X+J+CRBM=,iv:ao6gNzXvHpo9zyzyIxS78hCeiUJcoGNH8IWs+TccRnk=,tag:7bAtdp+Ta49z8qz99Phh+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
