apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: server
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: server
stringData:
  POSTGRES_PASSWORD: "change-me-postgres-admin"
  PAPERLESS_DB_PASSWORD: "change-me-paperless"
  MEALIE_DB_PASSWORD: "change-me-mealie"
  AUTHENTIK_DB_PASSWORD: "change-me-authentik"
