services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
      - ../data/uptime/:/app/data
    ports:
      - "3000:3001"
    labels:
      - docker-volume-backup.stop-during-backup=true
