apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: server
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/davidferneding/server.git
  ref:
    branch: main
  secretRef:
    name: flux-deploy-key
